'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.about': 'About',
    'nav.experience': 'Experience',
    'nav.projects': 'Projects',
    'nav.achievements': 'Achievements',
    'nav.techStack': 'Tech Stack',
    'nav.architecture': 'Architecture',
    'nav.aiResearch': 'AI Research',
    'nav.contact': 'Contact',
    'hero.title': 'Systems & AI',
    'hero.subtitle': 'Senior System Analyst / Systems & AI',
    'hero.name': 'Mansur Kakushkin',
    'hero.description': 'I design complex systems, integrations and AI-powered workflows — from business problem to architecture and implementation.',
    'hero.downloadCV': 'Download CV',
    'hero.contactMe': 'Contact Me',
    'hero.viewExperience': 'View Experience',
    'hero.selectedProjects': 'Selected Projects',
    'hero.scrollExplore': 'Scroll to explore',
    'about.title': 'About',
    'about.subtitle': 'I bridge business requirements, system architecture, data, integrations and implementation.',
    'about.description1': 'Senior System Analyst with 7+ years of experience designing complex information systems, integrations and automation for large enterprises including X5 and Sber.',
    'about.description2': 'My approach goes beyond collecting requirements and drawing diagrams. I work across the full spectrum — from understanding business processes and constraints to designing system architecture, APIs, data structures and implementation workflows.',
    'about.description3': 'I actively apply AI and automation to engineering work itself — using LLM, RAG, Graph RAG and knowledge graphs to accelerate system analysis, code understanding and documentation.',
    'about.rolesTitle': 'I work at the intersection of:',
    'about.roles': 'System Analysis,Business Analysis,Solution Architecture,Integration Architecture,API Design,Data,Automation,AI / LLM / RAG,Software Development',
    'experience.title': 'Experience',
    'experience.subtitle': 'Career Path',
    'experience.x5tech.senior.role': 'Senior System Analyst',
    'experience.x5tech.senior.period': 'Sep 2025 — Present (1 year)',
    'experience.x5tech.senior.location': 'Moscow / Remote',
    'experience.x5tech.senior.highlight1': 'Initiated and implemented AI tools in the development and requirements analysis process, changing the approach to delivery flow within the team.',
    'experience.x5tech.senior.highlight2': 'Digitized key services and brought all project documentation to a unified structured format; developed templates, references and usage rules.',
    'experience.x5tech.senior.highlight3': 'Formed and implemented standardized sets of contexts and rules (skill-packs) for using AI tools in analytics and development.',
    'experience.x5tech.senior.highlight4': 'Restructured the task decomposition process: creating tasks using AI and transferring them to development with AI tools support.',
    'experience.x5tech.senior.highlight5': 'Achieved 30-40% acceleration of "idea → feature implementation" cycle through optimization of task preparation and clarification.',
    'experience.x5tech.senior.highlight6': 'Reduced incident localization and elimination time in production by approximately 3x through improved context structuring and automation.',
    'experience.x5tech.senior.highlight7': 'Scaled the approach to other teams, conducted training and implementation of AI practices in cross-team collaboration.',
    'experience.x5tech.analyst.role': 'System Analyst',
    'experience.x5tech.analyst.period': 'Oct 2023 — Aug 2025 (1 year 11 months)',
    'experience.x5tech.analyst.location': 'Moscow / Remote',
    'experience.x5tech.analyst.highlight1': 'Within the "Tax Monitoring" project, analyzed and implemented FNS requirements for API integrations within a group of companies (9 legal entities).',
    'experience.x5tech.analyst.highlight2': 'Worked on integrations with SAP systems, interacted with related teams and participated in integration contract approvals.',
    'experience.x5tech.analyst.highlight3': 'Participated in designing microservice architecture of the platform, worked on external integrations, defined architecture of internal service interactions and designed DB structure.',
    'experience.x5tech.analyst.highlight4': 'Implemented schema-driven approach: automatically generated JSON Schema from XSD using Python scripts for form generation.',
    'experience.x5tech.analyst.highlight5': 'Designed mechanism for dynamic loading and versioning of XSD and JSON Schema without platform modifications.',
    'experience.x5tech.analyst.highlight6': 'Implemented infrastructure for XML document generation, conversion and validation according to XSD schemas.',
    'experience.x5tech.analyst.highlight7': 'Used PostgreSQL, ClickHouse, REST API and Airflow within the platform integration architecture.',
    'experience.x5tech.analyst.highlight8': 'Performed system and business analyst functions: requirements gathering, task creation for developers, prioritization and implementation control.',
    'experience.x5tech.analyst.highlight9': 'Independently wrote SQL queries, participated in centralized monitoring setup and transferred SQL metrics for platform monitoring.',
    'experience.x5tech.analyst.highlight10': 'Developed sequence diagrams, BPMN, UML diagrams and used PlantUML for solution design and documentation.',
    'experience.extrum.role': 'Business / System Analyst',
    'experience.extrum.period': 'Nov 2022 — Sep 2023 (11 months)',
    'experience.extrum.location': 'Moscow',
    'experience.extrum.highlight1': 'Formed and approved project documentation with Customers.',
    'experience.extrum.highlight2': 'Developed and approved internal service architecture, timelines, costs, integration interactions and design with customer and development team.',
    'experience.extrum.highlight3': 'Tested finished functionality, created tasks for improvements.',
    'experience.extrum.highlight4': 'Created technical documentation for small programs, controlled development and testing. Programs were implemented in the shortest time and optimized customer business units work several times.',
    'experience.extrum.highlight5': 'Formed development team and designer, managed backlog, priorities, timelines and task control.',
    'experience.smartauto.role': 'System Analyst',
    'experience.smartauto.period': 'Nov 2022 — Apr 2023 (6 months)',
    'experience.smartauto.location': 'Moscow',
    'experience.smartauto.highlight1': 'Created and approved project documentation for service implementation in Customer contour. Service successfully implemented and integrated with internal services for 3 large business Customers.',
    'experience.smartauto.highlight2': 'Generated database extracts for analytics and reporting on system operations.',
    'experience.smartauto.highlight3': 'Identified 15 critical blocking defects, described scenarios and hypotheses, prioritized and fixed them.',
    'experience.smartauto.highlight4': 'Prepared technical documentation for service functionality extensions and tested results. Added 4 features that simplified work for users and administrators.',
    'experience.smartauto.highlight5': 'Independently performed new service releases in Customer internal contour.',
    'experience.sber.role': 'System Analyst',
    'experience.sber.period': 'Dec 2018 — Oct 2022 (3 years 11 months)',
    'experience.sber.location': 'Moscow',
    'experience.sber.highlight1': 'Maintained integration interaction (request-response integration schemes, optimization of inter-system interaction), approved project documentation.',
    'experience.sber.highlight2': 'Participated in developing DSL language based on Python as a due diligence tool in corporate lending.',
    'experience.sber.highlight3': 'Created user and administrator manuals for internal service.',
    'experience.sber.highlight4': 'Built internal analytics service for audit team for data storage and information loading.',
    'experience.sber.highlight5': 'Identified technical/logical errors and formed proposals for improving Robot Lawyer service.',
    'experience.sber.highlight6': 'Developed and technically supported LegalTech projects, further developed automated due diligence process (AS IS research, TO BE process development).',
    'experience.sber.highlight7': 'Collaborated with DS team, participated in creating and improving service for document generation based on ML achieving 90% F-measure.',
    'experience.sber.highlight8': 'Managed backlog, coordinated team resources during sprint, prepared for release deployment.',
    'projects.title': 'Selected Projects',
    'projects.subtitle': 'Case Studies',
    'projects.tax.title': 'Tax Monitoring System',
    'projects.tax.subtitle': 'SAP / FNS / Microservices / PostgreSQL / ClickHouse / Airflow',
    'projects.tax.description': 'System integrated with SAP and corporate systems for Federal Tax Service monitoring. Microservice architecture serving 40+ users across 9 legal entities.',
    'projects.tax.metric1': '5x resource optimization',
    'projects.tax.metric2': '9 legal entities',
    'projects.tax.metric3': '40+ users',
    'projects.schema.title': 'Schema-driven Automation',
    'projects.schema.subtitle': 'XSD → JSON Schema → Python',
    'projects.schema.description': 'Automated pipeline for document schema processing, transforming XSD schemas into JSON Schema and generating processing scripts — reducing manual analyst work.',
    'projects.schema.metric1': '5x faster processing',
    'projects.schema.metric2': 'Reduced manual work',
    'projects.ai.title': 'AI / RAG Research',
    'projects.ai.subtitle': 'Graph RAG / Code Graph / AI Agents',
    'projects.ai.description': 'Research and prototyping of AI-powered systems for code analysis, knowledge graphs and automated system analysis using LLM, RAG and graph-based approaches.',
    'projects.viewCaseStudy': 'View Case Study',
    'casestudy.problem': 'Problem',
    'casestudy.context': 'Context',
    'casestudy.myRole': 'My Role',
    'casestudy.architecture': 'Architecture',
    'casestudy.solution': 'Technical Solution',
    'casestudy.challenges': 'Challenges',
    'casestudy.result': 'Result',
    'casestudy.technologies': 'Technologies',
    'casestudy.back': 'Back to Projects',
    'tax.problem': 'A large enterprise group needed to automate tax monitoring reporting to the Federal Tax Service (FNS). The existing process involved manual data extraction from multiple corporate systems including SAP, which was time-consuming, error-prone and difficult to scale across 9 legal entities.',
    'tax.context': 'The system needed to serve 40+ users across a group of 9 legal entities. Data sources included SAP ERP and other corporate systems. The architecture required microservices to handle different aspects of data processing, validation and reporting independently.',
    'tax.role1': 'System analysis and requirements gathering from business stakeholders',
    'tax.role2': 'Designing integration architecture between SAP, PostgreSQL, ClickHouse and internal systems',
    'tax.role3': 'Defining API contracts and data structures for microservice communication',
    'tax.role4': 'Technical documentation and architecture decision records',
    'tax.role5': 'Coordination between business, development and operations teams',
    'tax.arch': 'Microservice architecture with dedicated services for data extraction, transformation, validation and reporting. SAP integration layer handling data synchronization. PostgreSQL for transactional data, ClickHouse for analytical queries and reporting. Airflow orchestrating data pipelines.',
    'tax.solution1': 'REST API layer for inter-service communication with well-defined contracts',
    'tax.solution2': 'ETL pipelines orchestrated by Airflow for data extraction and transformation',
    'tax.solution3': 'Schema-driven data validation ensuring compliance with FNS requirements',
    'tax.solution4': 'Caching layer for frequently accessed reference data',
    'tax.solution5': 'Monitoring and alerting for data pipeline health',
    'tax.challenge1': 'Complex data structures across 9 different legal entities with varying configurations',
    'tax.challenge2': 'SAP integration requiring deep understanding of enterprise data models',
    'tax.challenge3': 'Strict compliance requirements from FNS with zero tolerance for data errors',
    'tax.challenge4': 'Performance requirements for large data volumes in analytical queries',
    'tax.result1': '5x optimization in time and resource usage through automation',
    'tax.result2': 'Successfully serving 40+ users across 9 legal entities',
    'tax.result3': 'Eliminated manual data extraction and validation errors',
    'tax.result4': 'Reduced report generation time from days to hours',
    'schema.problem': 'System analysts spent significant time manually processing XSD schemas, converting them to internal formats and creating documentation for development teams. Schema changes required repetitive manual work across multiple documents and code artifacts.',
    'schema.context': 'The workflow involved XSD schemas defining data structures for inter-system communication. With each schema change, analysts manually processed XSD, while development spent time implementing screen forms and parsing data from JSON/XML.',
    'schema.role1': 'Identified the automation opportunity in the schema processing workflow',
    'schema.role2': 'Designed the XSD → JSON Schema → Python transformation pipeline',
    'schema.role3': 'Implemented Python scripts for automated schema conversion and code generation',
    'schema.role4': 'Validated output accuracy against manual processing results',
    'schema.arch': 'Pipeline architecture: XSD source → parsing layer → JSON Schema generation → Python script generation → validation → output artifacts. Each stage is modular and can be extended for new schema types or output formats.',
    'schema.solution1': 'Python-based XSD parser extracting type definitions, constraints and relationships',
    'schema.solution2': 'Semi-automated JSON Schema generation from XSD considering business logic',
    'schema.solution3': 'Backend uses a library for JSON → XML conversion. JSON Schema is sent to frontend, which automatically renders form fields and collects data into FormData',
    'schema.solution4': 'Analyst only needs to upload updated JSON Schema when XSD changes — developers are not involved in the process',
    'schema.challenge1': 'Complex XSD features including namespaces, inheritance and custom types',
    'schema.challenge2': 'Maintaining accuracy across automated transformations',
    'schema.challenge3': 'Handling edge cases in schema definitions without human intervention',
    'schema.result1': '5x faster schema processing through automation',
    'schema.result2': 'Significantly reduced manual work for analysts and developers',
    'schema.result3': 'Faster turnaround on schema change requests',
    'schema.result4': 'Reduced errors in schema-to-code translation',
    'schema.result5': 'Development completely removed from the process — everything works automatically',
    'ai.problem': 'System analysts and engineers spend significant time understanding existing codebases, finding relevant context, analyzing dependencies and generating technical documentation. Traditional tools provide limited semantic understanding of code and architecture.',
    'ai.context': 'Modern software systems are complex with deep dependency chains, distributed architectures and extensive documentation. AI-powered approaches using LLM, RAG and graph-based models can provide deeper understanding and faster context retrieval than traditional search.',
    'ai.role1': 'Research and prototyping of AI-powered code analysis systems',
    'ai.role2': 'Designing graph-based models for code representation (AST, dependencies, architecture)',
    'ai.role3': 'Implementing RAG pipelines for code and documentation search',
    'ai.role4': 'Exploring MCP (Model Context Protocol) for AI agent architectures',
    'ai.role5': 'Evaluating tools and frameworks: LangChain, vector databases, graph databases',
    'ai.arch': 'Code → AST / dependencies → Graph → RAG → AI. The system transforms codebases into knowledge graphs with semantic embeddings, enabling natural language queries over code structure, documentation and architectural decisions.',
    'ai.solution1': 'Code parsing into AST and dependency graphs',
    'ai.solution2': 'Vector embeddings for semantic search across code and documentation',
    'ai.solution3': 'Graph RAG combining structured graph traversal with vector similarity',
    'ai.solution4': 'AI agents with tool use for automated code exploration and analysis',
    'ai.solution5': 'MCP integration for context-aware AI interactions',
    'ai.challenge1': 'Balancing graph complexity with query performance',
    'ai.challenge2': 'Handling diverse codebases and programming languages',
    'ai.challenge3': 'Ensuring accuracy of AI-generated analysis and recommendations',
    'ai.challenge4': 'Integrating with existing development workflows and tools',
    'ai.result1': 'Prototypes demonstrating semantic code search and analysis capabilities',
    'ai.result2': 'Frameworks for transforming codebases into queryable knowledge graphs',
    'ai.result3': 'Insights into practical applications of Graph RAG for engineering work',
    'ai.result4': 'Ongoing research into AI-assisted system analysis workflows',
    'achievements.title': 'Achievements',
    'achievements.subtitle': 'Measurable Results',
    'achievements.optimization.label': 'Resource Optimization',
    'achievements.optimization.description': 'Time and resource savings through system automation',
    'achievements.generation.label': 'Faster Generation',
    'achievements.generation.description': 'Document generation speed improvement',
    'achievements.broker.label': 'Broker Interaction',
    'achievements.broker.description': 'Faster broker integration processing',
    'achievements.cycle.label': 'Faster Cycle',
    'achievements.cycle.description': 'Idea to feature delivery acceleration',
    'achievements.patent.label': 'Patent',
    'achievements.patent.description': 'Registered patent for automated legal analysis system',
    'techStack.title': 'Technology Map',
    'techStack.subtitle': 'Technical Stack',
    'techStack.backend': 'Backend / Data',
    'techStack.integration': 'Integration',
    'techStack.frontend': 'Frontend',
    'techStack.infrastructure': 'Infrastructure',
    'techStack.ai': 'AI',
    'techStack.tools': 'Analyst Tools',
    'architecture.title': 'How I Think',
    'architecture.subtitle': 'From Problem to Result',
    'architecture.description': "I don't just document requirements — I work across the full spectrum from business problem understanding to architecture design and implementation.",
    'architecture.step1': 'Business Problem',
    'architecture.step2': 'Business Process',
    'architecture.step3': 'Requirements',
    'architecture.step4': 'System Context',
    'architecture.step5': 'Architecture',
    'architecture.step6': 'API / Data',
    'architecture.step7': 'Implementation',
    'architecture.step8': 'Automation / AI',
    'architecture.step9': 'Result',
    'aiResearch.title': 'AI & Research',
    'aiResearch.subtitle': 'System Analysis + Architecture + AI',
    'aiResearch.description': 'I actively explore how AI can transform system analysis and engineering work — not just as a chat tool, but as infrastructure for understanding code, documentation and architecture.',
    'aiResearch.llm.title': 'LLM & RAG Systems',
    'aiResearch.llm.description': 'Applying large language models with retrieval-augmented generation for code understanding, documentation and system analysis workflows.',
    'aiResearch.graph.title': 'Graph RAG & Code Graph',
    'aiResearch.graph.description': 'Exploring graph-based models for code analysis — transforming codebases into knowledge graphs for dependency analysis, context search and architecture understanding.',
    'aiResearch.semantic.title': 'Semantic Code Search',
    'aiResearch.semantic.description': 'Building systems that understand code semantically — enabling natural language queries over codebases, documentation and architectural decisions.',
    'aiResearch.agents.title': 'AI Agents & MCP',
    'aiResearch.agents.description': 'Developing AI agent architectures with Model Context Protocol for automated system analysis, requirement generation and technical documentation.',
    'aiResearch.analysis.title': 'AI-assisted Analysis',
    'aiResearch.analysis.description': 'Using AI to accelerate the analyst workflow itself — from requirement gathering and process modeling to architecture documentation and test generation.',
    'footer.title': "Let's work together",
    'footer.description': 'Open to senior system analyst, solution architecture and AI-focused engineering roles.',
    'footer.rights': 'All rights reserved',
    'footer.builtWith': 'Built with',
    'theme.toggle': 'Toggle theme',
    'language.toggle': 'Toggle language',
  },
  ru: {
    'nav.about': 'Обо мне',
    'nav.experience': 'Опыт',
    'nav.projects': 'Проекты',
    'nav.achievements': 'Достижения',
    'nav.techStack': 'Технологии',
    'nav.architecture': 'Архитектура',
    'nav.aiResearch': 'AI исследования',
    'nav.contact': 'Контакты',
    'hero.title': 'Системы и AI',
    'hero.subtitle': 'Системный аналитик / Системы и AI',
    'hero.name': 'Мансур Какушкин',
    'hero.description': 'Проектирую сложные системы, интеграции и AI-решения — от бизнес-задачи до архитектуры и реализации.',
    'hero.downloadCV': 'Скачать резюме',
    'hero.contactMe': 'Связаться',
    'hero.viewExperience': 'Посмотреть опыт',
    'hero.selectedProjects': 'Избранные проекты',
    'hero.scrollExplore': 'Листайте дальше',
    'about.title': 'Обо мне',
    'about.subtitle': 'Связываю бизнес-требования, системную архитектуру, данные, интеграции и реализацию.',
    'about.description1': 'Системный аналитик с 7+ годами опыта проектирования сложных информационных систем, интеграций и автоматизации для крупных предприятий, включая X5 и Сбер.',
    'about.description2': 'Мой подход выходит за рамки сбора требований и черчения диаграмм. Я работаю во всем спектре — от понимания бизнес-процессов и ограничений до проектирования системной архитектуры, API, структур данных и рабочих процессов реализации.',
    'about.description3': 'Активно применяю AI и автоматизацию в самой инженерной работе — использую LLM, RAG, Graph RAG и графы знаний для ускорения системного анализа, понимания кода и документации.',
    'about.rolesTitle': 'Работаю на стыке:',
    'about.roles': 'Системный анализ,Бизнес-анализ,Архитектура решений,Архитектура интеграций,Проектирование API,Данные,Автоматизация,AI / LLM / RAG,Разработка ПО',
    'experience.title': 'Опыт работы',
    'experience.subtitle': 'Карьерный путь',
    'experience.x5tech.senior.role': 'Старший системный аналитик',
    'experience.x5tech.senior.period': 'Сентябрь 2025 — настоящее время (1 год)',
    'experience.x5tech.senior.location': 'Москва / Удалённо',
    'experience.x5tech.senior.highlight1': 'Инициировал и реализовал внедрение AI-инструментов в процесс разработки и анализа требований, изменив подход к delivery-флоу внутри команды.',
    'experience.x5tech.senior.highlight2': 'Оцифровал ключевые сервисы и привёл всю проектную документацию к единому структурированному формату; разработал шаблоны, референсы и правила их использования.',
    'experience.x5tech.senior.highlight3': 'Сформировал и внедрил стандартизированные наборы контекстов и правил (skill-packs) для применения AI-инструментов в аналитике и разработке.',
    'experience.x5tech.senior.highlight4': 'Перестроил процесс декомпозиции задач: формирование задач с использованием AI и передача их в разработку с поддержкой AI-инструментов со стороны разработчиков.',
    'experience.x5tech.senior.highlight5': 'Добился ускорения цикла «идея → реализация фичи» на 30–40% за счёт оптимизации подготовки и уточнения задач.',
    'experience.x5tech.senior.highlight6': 'Сократил время локализации и устранения инцидентов в production примерно в 3 раза за счёт улучшения структурирования контекста и автоматизации анализа.',
    'experience.x5tech.senior.highlight7': 'Масштабировал подход на другие команды, проводил обучение и внедрение AI-практик в рамках кросс-командного взаимодействия.',
    'experience.x5tech.analyst.role': 'Системный аналитик',
    'experience.x5tech.analyst.period': 'Октябрь 2023 — Август 2025 (1 год 11 месяцев)',
    'experience.x5tech.analyst.location': 'Москва / Удалённо',
    'experience.x5tech.analyst.highlight1': 'В рамках проекта «Налоговый мониторинг» анализировал и реализовывал требования ФНС для API-интеграций внутри группы компаний (9 юридических лиц).',
    'experience.x5tech.analyst.highlight2': 'Прорабатывал интеграции с системами SAP, взаимодействовал со смежными командами и участвовал в согласовании интеграционных контрактов.',
    'experience.x5tech.analyst.highlight3': 'Участвовал в проектировании микросервисной архитектуры платформы, прорабатывал внешние интеграции, определял архитектуру взаимодействия внутренних сервисов и проектировал структуру БД.',
    'experience.x5tech.analyst.highlight4': 'Реализовал schema-driven подход: на основании XSD с использованием Python-скриптов автоматически формировал JSON Schema для генерации экранных форм.',
    'experience.x5tech.analyst.highlight5': 'Спроектировал механизм динамической загрузки и версионирования XSD и JSON Schema без необходимости доработки платформы.',
    'experience.x5tech.analyst.highlight6': 'Реализовал инфраструктуру формирования, конвертации и валидации XML-документов согласно XSD-схемам.',
    'experience.x5tech.analyst.highlight7': 'Использовал PostgreSQL, ClickHouse, REST API и Airflow в рамках интеграционной архитектуры платформы.',
    'experience.x5tech.analyst.highlight8': 'Выполнял функции системного и бизнес-аналитика: сбор и проработка требований, постановка задач разработчикам, приоритизация и контроль реализации.',
    'experience.x5tech.analyst.highlight9': 'Самостоятельно писал SQL-запросы, участвовал в настройке централизованного мониторинга и передавал SQL-метрики для мониторинга платформы.',
    'experience.x5tech.analyst.highlight10': 'Разрабатывал sequence diagrams, BPMN, UML-диаграммы и использовал PlantUML для проектирования и документирования решений.',
    'experience.extrum.role': 'Бизнес / Системный аналитик',
    'experience.extrum.period': 'Ноябрь 2022 — Сентябрь 2023 (11 месяцев)',
    'experience.extrum.location': 'Москва',
    'experience.extrum.highlight1': 'Формирование и согласование проектной документации с Заказчиками.',
    'experience.extrum.highlight2': 'Проработка и согласование внутренней архитектуры сервиса, сроков, стоимости, интеграционных взаимодействий и дизайна.',
    'experience.extrum.highlight3': 'Тестирование готового функционала, заведение задач на доработку.',
    'experience.extrum.highlight4': 'Создание технической документации, контроль разработки и тестирование. Программы реализованы в кратчайшие сроки и оптимизировали работу бизнес-подразделений в несколько раз.',
    'experience.extrum.highlight5': 'Формирование команды разработчиков и дизайнера, управление беклогом, приоритетами, сроками и контроль исполнения.',
    'experience.smartauto.role': 'Системный аналитик',
    'experience.smartauto.period': 'Ноябрь 2022 — Апрель 2023 (6 месяцев)',
    'experience.smartauto.location': 'Москва',
    'experience.smartauto.highlight1': 'Создание и согласование проектной документации по внедрению сервиса. Сервис успешно внедрён и интегрирован с внутренними сервисами у 3 Заказчиков из сегмента крупного бизнеса.',
    'experience.smartauto.highlight2': 'Формирование выгрузок из БД сервиса для аналитики и отчётности по работе системы.',
    'experience.smartauto.highlight3': 'Выявлено 15 критических дефектов, блокирующих работу; описание сценариев, приоритезация и устранение.',
    'experience.smartauto.highlight4': 'Подготовка технической документации по расширению функционала и тестирование. Добавлены 4 фичи, упростившие работу пользователям и администраторам.',
    'experience.smartauto.highlight5': 'Самостоятельно выполнял новые релизы сервиса во внутреннем контуре Заказчиков.',
    'experience.sber.role': 'Системный аналитик',
    'experience.sber.period': 'Декабрь 2018 — Октябрь 2022 (3 года 11 месяцев)',
    'experience.sber.location': 'Москва',
    'experience.sber.highlight1': 'Поддержка интеграционного взаимодействия (схемы запрос-ответ, оптимизация межсистемного взаимодействия), согласование проектной документации.',
    'experience.sber.highlight2': 'Участие в разработке языка DSL на базе Python как инструмента due diligence в корпоративном кредитовании.',
    'experience.sber.highlight3': 'Создание руководства пользователя и администратора для внутреннего сервиса.',
    'experience.sber.highlight4': 'Создание внутреннего аналитического сервиса для команды аудиторов для хранения данных и загрузки информации.',
    'experience.sber.highlight5': 'Выявление технических/логических ошибок и формирование предложений по улучшению работы сервиса Робот юрист.',
    'experience.sber.highlight6': 'Разработка и техническая поддержка проектов LegalTech, развитие автоматизированного процесса due diligence (исследование AS IS, разработка TO BE процессов).',
    'experience.sber.highlight7': 'При взаимодействии с командой DS участвовал в создании и улучшении до 90% F-меры сервиса для формирования документов на основе ML.',
    'experience.sber.highlight8': 'Управление бэклогом, координация ресурсов команды во время спринта, подготовка к развёртыванию релизов.',
    'projects.title': 'Избранные проекты',
    'projects.subtitle': 'Кейсы',
    'projects.tax.title': 'Система налогового мониторинга',
    'projects.tax.subtitle': 'SAP / ФНС / Микросервисы / PostgreSQL / ClickHouse / Airflow',
    'projects.tax.description': 'Система, интегрированная с SAP и корпоративными системами для мониторинга ФНС. Микросервисная архитектура для 40+ пользователей в 9 юридических лицах.',
    'projects.tax.metric1': 'Оптимизация ресурсов в 5 раз',
    'projects.tax.metric2': '9 юридических лиц',
    'projects.tax.metric3': '40+ пользователей',
    'projects.schema.title': 'Автоматизация на основе схем',
    'projects.schema.subtitle': 'XSD → JSON Schema → Python',
    'projects.schema.description': 'Автоматизированный конвейер обработки схем документов, преобразующий XSD-схемы в JSON Schema и генерирующий скрипты обработки — снижение ручной работы аналитика.',
    'projects.schema.metric1': 'Обработка в 5 раз быстрее',
    'projects.schema.metric2': 'Снижение ручной работы',
    'projects.ai.title': 'AI / RAG исследования',
    'projects.ai.subtitle': 'Graph RAG / Code Graph / AI Agents',
    'projects.ai.description': 'Исследование и прототипирование AI-систем для анализа кода, графов знаний и автоматизированного системного анализа с использованием LLM, RAG и графовых подходов.',
    'projects.viewCaseStudy': 'Посмотреть кейс',
    'casestudy.problem': 'Проблема',
    'casestudy.context': 'Контекст',
    'casestudy.myRole': 'Моя роль',
    'casestudy.architecture': 'Архитектура',
    'casestudy.solution': 'Техническое решение',
    'casestudy.challenges': 'Сложности',
    'casestudy.result': 'Результат',
    'casestudy.technologies': 'Технологии',
    'casestudy.back': 'Назад к проектам',
    'tax.problem': 'Крупной группе предприятий требовалось автоматизировать отчётность по налоговому мониторингу в ФНС. Существующий процесс включал ручное извлечение данных из множества корпоративных систем, включая SAP, что было трудоёмким, подверженным ошибкам и сложно масштабировалось на 9 юридических лиц.',
    'tax.context': 'Система должна была обслуживать 40+ пользователей в группе из 9 юридических лиц. Источниками данных выступали SAP ERP и другие корпоративные системы. Архитектура требовала микросервисов для обработки различных аспектов извлечения данных, валидации и отчётности.',
    'tax.role1': 'Системный анализ и сбор требований от бизнес-стейкхолдеров',
    'tax.role2': 'Проектирование интеграционной архитектуры между SAP, PostgreSQL, ClickHouse и внутренними системами',
    'tax.role3': 'Определение API-контрактов и структур данных для микросервисного взаимодействия',
    'tax.role4': 'Техническая документация и записи архитектурных решений',
    'tax.role5': 'Координация между бизнесом, разработкой и эксплуатацией',
    'tax.arch': 'Микросервисная архитектура с выделенными сервисами для извлечения, трансформации, валидации данных и отчётности. Интеграционный слой SAP для синхронизации данных. PostgreSQL для транзакционных данных, ClickHouse для аналитических запросов и отчётности. Airflow для оркестрации пайплайнов данных.',
    'tax.solution1': 'REST API слой для межсервисного взаимодействия с чётко определёнными контрактами',
    'tax.solution2': 'ETL-пайплайны под управлением Airflow для извлечения и трансформации данных',
    'tax.solution3': 'Schema-driven валидация данных для обеспечения соответствия требованиям ФНС',
    'tax.solution4': 'Слой кеширования для часто запрашиваемых справочных данных',
    'tax.solution5': 'Мониторинг и алертинг для состояния пайплайнов данных',
    'tax.challenge1': 'Сложные структуры данных в 9 различных юридических лицах с разными конфигурациями',
    'tax.challenge2': 'Интеграция с SAP, требующая глубокого понимания корпоративных моделей данных',
    'tax.challenge3': 'Жёсткие требования ФНС к соответствию с нулевой толерантностью к ошибкам данных',
    'tax.challenge4': 'Требования к производительности для больших объёмов данных в аналитических запросах',
    'tax.result1': '5-кратная оптимизация по времени и использованию ресурсов за счёт автоматизации',
    'tax.result2': 'Успешное обслуживание 40+ пользователей в 9 юридических лицах',
    'tax.result3': 'Устранено ручное извлечение данных и ошибки валидации',
    'tax.result4': 'Сокращено время генерации отчётов с дней до часов',
    'schema.problem': 'Системные аналитики тратили значительное время на ручную обработку XSD-схем, конвертацию во внутренние форматы и создание документации для команд разработки. Изменения схем требовали повторной ручной работы по множеству документов и артефактов кода.',
    'schema.context': 'Рабочий процесс включал XSD-схемы, определяющие структуры данных для межсистемного взаимодействия. При каждом изменении схем аналитики вручную обрабатывали XSD, а разработка тратила время на реализацию экранных форм и парсинг данных из JSON/XML.',
    'schema.role1': 'Выявил возможность автоматизации в процессе обработки схем',
    'schema.role2': 'Спроектировал конвейер трансформации XSD → JSON Schema → Python',
    'schema.role3': 'Реализовал Python-скрипты для автоматической конвертации схем и генерации кода',
    'schema.role4': 'Проверил точность результатов относительно ручной обработки',
    'schema.arch': 'Архитектура конвейера: XSD источник → слой парсинга → генерация JSON Schema → генерация Python-скриптов → валидация → выходные артефакты. Каждый этап модульный и может быть расширен для новых типов схем или форматов вывода.',
    'schema.solution1': 'Парсер XSD на Python, извлекающий определения типов, ограничения и связи',
    'schema.solution2': 'Полуавтоматическая генерация JSON Schema из XSD с учётом бизнес-логики',
    'schema.solution3': 'Бэкенд использует библиотеку для конвертации JSON → XML. JSON Schema передаётся на фронтенд, который автоматически рисует поля формы и собирает данные в FormData',
    'schema.solution4': 'Аналитику достаточно загружать обновлённые JSON Schema при изменении XSD — разработчики не участвуют в процессе',
    'schema.challenge1': 'Сложные возможности XSD, включая пространства имён, наследование и пользовательские типы',
    'schema.challenge2': 'Поддержание точности при автоматических трансформациях',
    'schema.challenge3': 'Обработка граничных случаев в определениях схем без вмешательства человека',
    'schema.result1': '5-кратное ускорение обработки схем за счёт автоматизации',
    'schema.result2': 'Значительное сокращение ручной работы аналитиков и разработчиков',
    'schema.result3': 'Ускорение реагирования на запросы изменений схем',
    'schema.result4': 'Снижение ошибок при переводе из схемы в код',
    'schema.result5': 'Разработка полностью исключена из процесса — всё работает автоматически',
    'ai.problem': 'Системные аналитики и инженеры тратят значительное время на понимание существующих кодовых баз, поиск релевантного контекста, анализ зависимостей и генерацию технической документации. Традиционные инструменты обеспечивают ограниченное семантическое понимание кода и архитектуры.',
    'ai.context': 'Современные программные системы сложны, с глубокими цепочками зависимостей, распределёнными архитектурами и обширной документацией. AI-подходы с использованием LLM, RAG и графовых моделей обеспечивают более глубокое понимание и более быстрый поиск контекста, чем традиционный поиск.',
    'ai.role1': 'Исследование и прототипирование AI-систем анализа кода',
    'ai.role2': 'Проектирование графовых моделей для представления кода (AST, зависимости, архитектура)',
    'ai.role3': 'Реализация RAG-пайплайнов для поиска по коду и документации',
    'ai.role4': 'Исследование MCP (Model Context Protocol) для архитектур AI-агентов',
    'ai.role5': 'Оценка инструментов и фреймворков: LangChain, векторные БД, графовые БД',
    'ai.arch': 'Код → AST / зависимости → Граф → RAG → AI. Система преобразует кодовые базы в графы знаний с семантическими эмбеддингами, обеспечивая запросы на естественном языке по структуре кода, документации и архитектурным решениям.',
    'ai.solution1': 'Парсинг кода в AST и графы зависимостей',
    'ai.solution2': 'Векторные эмбеддинги для семантического поиска по коду и документации',
    'ai.solution3': 'Graph RAG, объединяющий структурный обход графа с векторным сходством',
    'ai.solution4': 'AI-агенты с использованием инструментов для автоматизированного исследования и анализа кода',
    'ai.solution5': 'Интеграция MCP для контекстных AI-взаимодействий',
    'ai.challenge1': 'Балансировка сложности графа с производительностью запросов',
    'ai.challenge2': 'Обработка разнообразных кодовых баз и языков программирования',
    'ai.challenge3': 'Обеспечение точности AI-анализа и рекомендаций',
    'ai.challenge4': 'Интеграция с существующими рабочими процессами и инструментами разработки',
    'ai.result1': 'Прототипы, демонстрирующие возможности семантического поиска и анализа кода',
    'ai.result2': 'Фреймворки для преобразования кодовых баз в запрашиваемые графы знаний',
    'ai.result3': 'Понимание практических применений Graph RAG для инженерной работы',
    'ai.result4': 'Продолжающиеся исследования AI-ассистированных процессов системного анализа',
    'achievements.title': 'Достижения',
    'achievements.subtitle': 'Измеримые результаты',
    'achievements.optimization.label': 'Оптимизация ресурсов',
    'achievements.optimization.description': 'Экономия времени и ресурсов через автоматизацию систем',
    'achievements.generation.label': 'Ускорение генерации',
    'achievements.generation.description': 'Улучшение скорости генерации документов',
    'achievements.broker.label': 'Взаимодействие с брокерами',
    'achievements.broker.description': 'Ускорение обработки интеграций с брокерами',
    'achievements.cycle.label': 'Ускорение цикла',
    'achievements.cycle.description': 'Ускорение доставки от идеи до фичи',
    'achievements.patent.label': 'Патент',
    'achievements.patent.description': 'Зарегистрированный патент на автоматизированную систему юридического анализа',
    'techStack.title': 'Карта технологий',
    'techStack.subtitle': 'Технический стек',
    'techStack.backend': 'Бэкенд / Данные',
    'techStack.integration': 'Интеграции',
    'techStack.frontend': 'Фронтенд',
    'techStack.infrastructure': 'Инфраструктура',
    'techStack.ai': 'AI',
    'techStack.tools': 'Инструменты аналитика',
    'architecture.title': 'Как я мыслю',
    'architecture.subtitle': 'От проблемы к результату',
    'architecture.description': 'Я не просто документирую требования — я работаю во всем спектре: от понимания бизнес-задачи до проектирования архитектуры и реализации.',
    'architecture.step1': 'Бизнес-задача',
    'architecture.step2': 'Бизнес-процесс',
    'architecture.step3': 'Требования',
    'architecture.step4': 'Системный контекст',
    'architecture.step5': 'Архитектура',
    'architecture.step6': 'API / Данные',
    'architecture.step7': 'Реализация',
    'architecture.step8': 'Автоматизация / AI',
    'architecture.step9': 'Результат',
    'aiResearch.title': 'AI и исследования',
    'aiResearch.subtitle': 'Системный анализ + Архитектура + AI',
    'aiResearch.description': 'Активно исследую, как AI может трансформировать системный анализ и инженерную работу — не просто как чат-инструмент, а как инфраструктуру для понимания кода, документации и архитектуры.',
    'aiResearch.llm.title': 'LLM и RAG системы',
    'aiResearch.llm.description': 'Применение больших языковых моделей с генерацией с дополнительным поиском для понимания кода, документации и рабочих процессов системного анализа.',
    'aiResearch.graph.title': 'Graph RAG и Code Graph',
    'aiResearch.graph.description': 'Исследование графовых моделей для анализа кода — преобразование кодовых баз в графы знаний для анализа зависимостей, контекстного поиска и понимания архитектуры.',
    'aiResearch.semantic.title': 'Семантический поиск кода',
    'aiResearch.semantic.description': 'Создание систем, которые понимают код семантически — обеспечивая запросы на естественном языке по кодовым базам, документации и архитектурным решениям.',
    'aiResearch.agents.title': 'AI агенты и MCP',
    'aiResearch.agents.description': 'Разработка архитектур AI-агентов с Model Context Protocol для автоматизированного системного анализа, генерации требований и технической документации.',
    'aiResearch.analysis.title': 'AI-ассистированный анализ',
    'aiResearch.analysis.description': 'Использование AI для ускорения самого рабочего процесса аналитика — от сбора требований и моделирования процессов до документирования архитектуры и генерации тестов.',
    'footer.title': 'Давайте работать вместе',
    'footer.description': 'Открыт для позиций системного аналитика, архитектора решений и AI-инженера.',
    'footer.rights': 'Все права защищены',
    'footer.builtWith': 'Создано с помощью',
    'theme.toggle': 'Переключить тему',
    'language.toggle': 'Переключить язык',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
