'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.about': 'About',
    'nav.experience': 'Experience',
    'nav.projects': 'Projects',
    'nav.achievements': 'Achievements',
    'nav.techStack': 'Tech Stack',
    'nav.architecture': 'Architecture',
    'nav.aiResearch': 'AI Research',
    'nav.contact': 'Contact',
    'hero.title': 'Systems & AI',
    'hero.subtitle': 'Senior System Analyst / Systems & AI',
    'hero.name': 'Mansur Kakushkin',
    'hero.description': 'I design complex systems, integrations and AI-powered workflows — from business problem to architecture and implementation.',
    'hero.downloadCV': 'Download CV',
    'hero.contactMe': 'Contact Me',
    'hero.viewExperience': 'View Experience',
    'hero.selectedProjects': 'Selected Projects',
    'hero.scrollExplore': 'Scroll to explore',
    'about.title': 'About',
    'about.subtitle': 'I connect business requirements, system architecture, data, integrations and implementation.',
    'about.description1': 'Senior System Analyst with 7+ years of experience designing complex information systems, integrations and automation for large enterprises including X5 and Sber.',
    'about.description2': 'My approach goes beyond collecting requirements and drawing diagrams. I work across the full spectrum — from understanding business processes and constraints to designing system architecture, APIs, data structures and implementation workflows.',
    'about.description3': 'I actively apply AI and automation to engineering work itself — using LLM, RAG, Graph RAG and knowledge graphs to accelerate system analysis, code understanding and documentation. I also design and build production-oriented AI systems — including AI Code Knowledge Platform, a full-stack platform for automated code knowledge extraction, graph-based analysis and AI-generated documentation.',
    'about.rolesTitle': 'I work at the intersection of:',
    'about.roles': 'System Analysis,Business Analysis,Solution Architecture,Integration Architecture,API Design,Data,Automation,AI / LLM / RAG,Software Development',
    'experience.title': 'Experience',
    'experience.subtitle': 'Career Path',
    'experience.x5tech.company': 'X5 Tech',
    'experience.x5tech.senior.role': 'Senior System Analyst',
    'experience.x5tech.senior.period': 'Sep 2025 — Present (1 year)',
    'experience.x5tech.senior.location': 'Moscow / Remote',
    'experience.x5tech.senior.highlight1': 'Initiated and implemented AI tools in the development and requirements analysis process, changing the approach to delivery flow within the team.',
    'experience.x5tech.senior.highlight2': 'Digitized key services and brought all project documentation to a unified structured format; developed templates, references and usage rules.',
    'experience.x5tech.senior.highlight3': 'Restructured the task decomposition process: creating tasks using AI and transferring them to development with AI tools support.',
    'experience.x5tech.senior.highlight4': 'Achieved 30-40% acceleration of "idea → feature implementation" cycle through optimization of task preparation and clarification.',
    'experience.x5tech.senior.highlight5': 'Reduced incident localization and elimination time in production by approximately 3x through improved context structuring and automation.',
    'experience.x5tech.senior.highlight6': 'Scaled the approach to other teams, conducted training and implementation of AI practices in cross-team collaboration.',
    'experience.x5tech.senior.highlight7': 'Designed and built AI Code Knowledge Platform — a full-stack system for automated code knowledge extraction using Graph RAG, AI agents and MCP, generating domain, database, architecture and functional documentation from source code.',
    'experience.x5tech.analyst.role': 'System Analyst',
    'experience.x5tech.analyst.period': 'Oct 2023 — Aug 2025 (1 year 11 months)',
    'experience.x5tech.analyst.location': 'Moscow / Remote',
    'experience.x5tech.analyst.highlight1': 'Within the "Tax Monitoring" project, analyzed and implemented FNS requirements for API integrations within a group of companies (9 legal entities).',
    'experience.x5tech.analyst.highlight2': 'Designed microservice architecture, worked on SAP integrations, external services, defined internal service interactions and DB structure.',
    'experience.x5tech.analyst.highlight3': 'Implemented schema-driven approach: semi-automatically generated JSON Schema from XSD, designed a mechanism for creating screen forms from JSON schemas that auto-generate for a specific XSD version — enabling analysts to update schemas and forms independently without developer involvement.',
    'experience.x5tech.analyst.highlight4': 'Performed system and business analyst functions: requirements gathering, task creation for developers, prioritization and implementation control.',
    'experience.x5tech.analyst.highlight5': 'Built monitoring dashboards in Grafana and implemented alert logic for production system health tracking.',
    'experience.extrum.company': 'Extrum',
    'experience.extrum.role': 'Business / System Analyst',
    'experience.extrum.period': 'Nov 2022 — Sep 2023 (11 months)',
    'experience.extrum.location': 'Astana',
    'experience.aiharness.company': 'AI Harness Engineering',
    'experience.aiharness.role': 'AI Harness Engineer / System Analyst',
    'experience.aiharness.period': '2024 — Present',
    'experience.aiharness.location': 'Moscow / Remote',
    'experience.aiharness.highlight1': 'Designed and built AI Code Knowledge Platform — an end-to-end platform that extracts verifiable knowledge from source code through structural code graphs, AI agents and semantic knowledge bases.',
    'experience.aiharness.highlight2': 'Architected Graph RAG pipeline: GitLab → Code Graph → Graph MCP → AI Agent → Documentation, with automated generation of domain, database, architecture and functional documentation.',
    'experience.aiharness.highlight3': 'Built AI chat workspace with multi-project MCP integrations (Confluence, Figma, Kaiten, Exchange), subagent execution tracking and token/cost monitoring.',
    'experience.aiharness.highlight4': 'Implemented job orchestration, GitLab auto-sync and Docker-based runtime management for Memgraph, Graph MCP and AI agent containers.',
    'experience.extrum.highlight1': 'Formed and approved project documentation with Customers.',
    'experience.extrum.highlight2': 'Developed and approved internal service architecture, timelines, costs, integration interactions and design with customer and development team.',
    'experience.extrum.highlight3': 'Tested finished functionality, created tasks for improvements.',
    'experience.extrum.highlight4': 'Created technical documentation for small programs, controlled development and testing. Programs were implemented in the shortest time and optimized customer business units work several times.',
    'experience.extrum.highlight5': 'Formed development team and designer, managed backlog, priorities, timelines and task control.',
    'experience.smartauto.company': 'Smart Automation',
    'experience.smartauto.role': 'System Analyst',
    'experience.smartauto.period': 'Nov 2022 — Apr 2023 (6 months)',
    'experience.smartauto.location': 'Remote',
    'experience.smartauto.highlight1': 'Created and approved project documentation for service implementation in Customer contour. Service successfully implemented and integrated with internal services for 3 large business Customers.',
    'experience.smartauto.highlight2': 'Generated database extracts for analytics and reporting on system operations.',
    'experience.smartauto.highlight3': 'Identified 15 critical blocking defects, described scenarios and hypotheses, prioritized and fixed them.',
    'experience.smartauto.highlight4': 'Prepared technical documentation for service functionality extensions and tested results. Added 4 features that simplified work for users and administrators.',
    'experience.smartauto.highlight5': 'Independently performed new service releases in Customer internal contour.',
    'experience.sber.role': 'System Analyst',
    'experience.sber.period': 'Dec 2018 — Oct 2022 (3 years 11 months)',
    'experience.sber.location': 'Moscow',
    'experience.sber.highlight1': 'Participated in developing DSL language based on Python as a due diligence tool in corporate lending.',
    'experience.sber.highlight2': 'Built internal analytics service for audit team for data storage and information loading.',
    'experience.sber.highlight3': 'Identified technical/logical errors and formed proposals for improving Robot Lawyer service.',
    'experience.sber.highlight4': 'Developed and technically supported LegalTech projects, further developed automated due diligence process (AS IS research, TO BE process development).',
    'experience.sber.highlight5': 'Collaborated with DS team, participated in creating and improving service for document generation based on ML achieving 90% F-measure.',
    'experience.sber.highlight6': 'Managed backlog, coordinated team resources during sprint, prepared for release deployment.',
    'projects.title': 'Selected Projects',
    'projects.subtitle': 'Case Studies',
    'projects.tax.title': 'Tax Monitoring System',
    'projects.tax.subtitle': 'SAP / FNS / Microservices / PostgreSQL / ClickHouse / Airflow',
    'projects.tax.description': 'System integrated with SAP and corporate systems for Federal Tax Service monitoring. Microservice architecture serving 40+ users across 9 legal entities.',
    'projects.tax.metric1': '5x resource optimization',
    'projects.tax.metric2': '9 legal entities',
    'projects.tax.metric3': '40+ users',
    'projects.schema.title': 'Schema-driven Automation',
    'projects.schema.subtitle': 'XSD → JSON Schema → Python',
    'projects.schema.description': 'Automated pipeline for document schema processing, transforming XSD schemas into JSON Schema and generating processing scripts — reducing manual analyst work.',
    'projects.schema.metric1': '5x faster processing',
    'projects.schema.metric2': 'Reduced manual work',
    'projects.aiDelivery.title': 'AI Delivery Transformation',
    'projects.aiDelivery.subtitle': 'Skill-packs / Context Structuring / AI Harness',
    'projects.aiDelivery.description': 'End-to-end AI transformation of delivery processes at X5 Tech. Created standardized skill-packs for AI tools, restructured task decomposition workflows, and built AI Harness infrastructure — reducing idea-to-feature cycle by 30-40%.',
    'projects.aiDelivery.metric1': '30-40% faster delivery',
    'projects.aiDelivery.metric2': '3x faster incident resolution',
    'projects.aiDelivery.metric3': 'Scaled to multiple teams',
    'projects.ai.title': 'AI Code Knowledge Platform',
    'projects.ai.subtitle': 'Graph RAG / AI Agents / MCP / Knowledge Graph',
    'projects.ai.description': 'Designed and built an end-to-end platform for automated code knowledge extraction from source code. Transforms repositories into knowledge graphs, generates documentation through AI agents and provides AI chat with multi-project context and MCP integrations.',
    'projects.ai.metric1': 'Full-stack platform',
    'projects.ai.metric2': '4 doc pipelines',
    'projects.ai.metric3': 'AI chat + MCP',
    'projects.viewCaseStudy': 'View Case Study',
    'casestudy.problem': 'Problem',
    'casestudy.context': 'Context',
    'casestudy.myRole': 'My Role',
    'casestudy.architecture': 'Architecture',
    'casestudy.solution': 'Technical Solution',
    'casestudy.challenges': 'Challenges',
    'casestudy.result': 'Result',
    'casestudy.technologies': 'Technologies',
    'casestudy.back': 'Back to Projects',
    'casestudy.label': 'Case Study',
    'tax.problem': 'A large enterprise group required a new automated tax monitoring system — AIS Tax 3 — to replace the manual reporting process to the Federal Tax Service (FNS). The existing workflow involved extracting data from multiple corporate systems including SAP, which was time-consuming and error-prone. The entire solution was designed with a focus on automating user workflows across 9 legal entities.',
    'tax.context': 'The system needed to serve 40+ users across a group of 9 legal entities. Data sources included SAP ERP and other corporate systems. The architecture required microservices to handle different aspects of data processing, validation and reporting independently.',
    'tax.role1': 'System analysis and requirements gathering from business stakeholders',
    'tax.role2': 'Designing integration architecture between SAP, PostgreSQL, ClickHouse and internal systems',
    'tax.role3': 'Defining API contracts and data structures for microservice communication',
    'tax.role4': 'Technical documentation and architecture decision records',
    'tax.role5': 'Coordination between business, development and operations teams',
    'tax.arch': 'Microservice architecture with dedicated services for data extraction, transformation, validation and reporting. SAP integration layer handling data synchronization. PostgreSQL for transactional data, ClickHouse for analytical queries and reporting. Airflow orchestrating data pipelines.',
    'tax.solution1': 'REST API layer for inter-service communication with well-defined contracts',
    'tax.solution2': 'ETL pipelines orchestrated by Airflow for data extraction and transformation',
    'tax.solution3': 'Schema-driven data validation ensuring compliance with FNS requirements',
    'tax.solution4': 'Caching layer for frequently accessed reference data',
    'tax.solution5': 'Monitoring and alerting for data pipeline health',
    'tax.challenge1': 'Complex data structures across 9 different legal entities with varying configurations',
    'tax.challenge2': 'SAP integration requiring deep understanding of enterprise data models',
    'tax.challenge3': 'Strict compliance requirements from FNS with zero tolerance for data errors',
    'tax.challenge4': 'Performance requirements for large data volumes in analytical queries',
    'tax.result1': '5x optimization in time and resource usage through automation',
    'tax.result2': 'Successfully serving 40+ users across 9 legal entities',
    'tax.result3': 'Eliminated manual data extraction and validation errors',
    'tax.result4': 'Reduced report generation time from days to hours',
    'schema.problem': 'Previously, for every XSD schema developers had to manually build screen forms — a process that required involvement for each new schema version. This created a bottleneck: any XSD change meant developer work to update the corresponding forms.',
    'schema.context': 'A universal mechanism was designed: JSON Schema is generated semi-automatically from XSD and sent to the frontend, which automatically renders form fields for that specific XSD version. Now when an XSD changes, the analyst only needs to update the JSON Schema — the screen forms adapt automatically without developer involvement.',
    'schema.role1': 'Identified the automation opportunity in the schema processing workflow',
    'schema.role2': 'Designed the XSD → JSON Schema → Python transformation pipeline',
    'schema.role3': 'Implemented Python scripts for automated schema conversion and code generation',
    'schema.role4': 'Validated output accuracy against manual processing results',
    'schema.arch': 'Pipeline architecture: XSD source → parsing layer → JSON Schema generation → Python script generation → validation → output artifacts. Each stage is modular and can be extended for new schema types or output formats.',
    'schema.solution1': 'Python-based XSD parser extracting type definitions, constraints and relationships',
    'schema.solution2': 'Semi-automated JSON Schema generation from XSD considering business logic',
    'schema.solution3': 'Backend uses a library for JSON → XML conversion. JSON Schema is sent to frontend, which automatically renders form fields and collects data into FormData',
    'schema.solution4': 'Analyst only needs to upload updated JSON Schema when XSD changes — developers are not involved in the process',
    'schema.challenge1': 'Complex XSD features including namespaces, inheritance and custom types',
    'schema.challenge2': 'Maintaining accuracy across automated transformations',
    'schema.challenge3': 'Handling edge cases in schema definitions without human intervention',
    'schema.result1': '5x faster schema processing through automation',
    'schema.result2': 'Significantly reduced manual work for analysts and developers',
    'schema.result3': 'Faster turnaround on schema change requests',
    'schema.result4': 'Reduced errors in schema-to-code translation',
    'schema.result5': 'Development completely removed from the process — everything works automatically',
    'ai.problem': 'System analysts and engineers spend significant time understanding existing codebases — tracing dependencies, finding context and writing documentation manually. Knowledge about systems lives in people\'s heads and scattered documents, making onboarding slow and analysis error-prone.',
    'ai.context': 'Modern enterprise systems have deep dependency chains and distributed architectures. The goal was to build a platform that automatically extracts structured knowledge from source code and turns it into queryable documentation — so analysts, engineers, support teams, testers and managers can understand systems faster without reading thousands of lines of code. The platform also serves as an onboarding tool for new team members.',
    'ai.role1': 'Designed the product concept and defined capabilities for multiple user roles: analysts, engineers, support, testers and managers',
    'ai.role2': 'Built the entire system independently — from architecture to working product ready for team adoption',
    'ai.role3': 'Implemented automated documentation generation covering domain models, database schemas, architecture and API',
    'ai.role4': 'Created interactive AI workspace where analysts can ask questions about codebases in natural language',
    'ai.role5': 'Designed integration layer connecting the platform with existing enterprise tools and workflows',
    'ai.arch': 'The platform connects to source code repositories, automatically builds a structured understanding of the codebase and uses AI agents to generate documentation, answer questions and extract knowledge. Everything works through a single web interface with no manual setup required per repository.',
    'ai.solution1': 'Automatic codebase analysis: dependency graphs, module relationships and architectural patterns extracted without manual effort',
    'ai.solution2': 'Four documentation pipelines: domain, database, architecture and functional — generated by AI agents reading the code',
    'ai.solution3': 'AI chat with full codebase context: ask questions in natural language, get answers grounded in actual source code',
    'ai.solution4': 'Knowledge base: documentation is indexed semantically, so the AI can find relevant context across all projects',
    'ai.solution5': 'Enterprise integrations: connects to Confluence, Figma, Kaiten and email for unified workflow',
    'ai.challenge1': 'Making the platform work for large real-world repositories without manual configuration',
    'ai.challenge2': 'Ensuring AI-generated documentation is accurate and useful, not just plausible-sounding text',
    'ai.challenge3': 'Keeping knowledge up-to-date as code changes — not a one-time export but a living system',
    'ai.challenge4': 'Building something that analysts actually want to use, not just another internal tool',
    'ai.result1': 'Full-stack product with automated documentation generation, AI chat and knowledge base',
    'ai.result2': 'Teams can understand a new codebase in hours instead of days — analysts, support, testers and new hires',
    'ai.result3': 'Documentation stays current through automatic synchronization with code repositories',
    'ai.result4': 'Ready for deployment and adoption by development, analytics, support and management teams',
    'aiDelivery.problem': 'X5 Tech engineering teams faced challenges in adopting AI tools effectively. Each team used AI differently, context was poorly structured, and task decomposition remained manual. This created inconsistent quality and slow delivery cycles.',
    'aiDelivery.context': 'Large enterprise with multiple development teams working on web applications across different business domains. Need to standardize AI adoption while maintaining flexibility for different team contexts and project types.',
    'aiDelivery.role1': 'Created standardized skill-packs — sets of contexts, rules and templates for using AI tools in analytics and development',
    'aiDelivery.role2': 'Restructured task decomposition process: AI-assisted task creation with structured prompts and transfer to development',
    'aiDelivery.role3': 'Built AI Harness infrastructure — software layer around LLMs providing tool orchestration, memory and context management',
    'aiDelivery.role4': 'Implemented context structuring patterns for reliable AI agent behavior',
    'aiDelivery.role5': 'Trained and scaled AI practices across multiple teams through workshops and documentation',
    'aiDelivery.arch': 'Skill-packs → Context Templates → AI Tools → Harness Layer → Development Flow. The system provides standardized AI interaction patterns with structured contexts, enabling consistent quality across teams while allowing customization per project.',
    'aiDelivery.solution1': 'Skill-packs: curated sets of prompts, rules and context templates for specific tasks (requirements analysis, code review, documentation)',
    'aiDelivery.solution2': 'AI Harness: software infrastructure around LLMs providing tool management, output control and result monitoring',
    'aiDelivery.solution3': 'Structured task decomposition: AI generates task breakdowns with acceptance criteria, developers review and implement with AI support',
    'aiDelivery.solution4': 'Context management system: maintains relevant context across conversations and tool interactions',
    'aiDelivery.solution5': 'MCP (Model Context Protocol) integration for connecting AI agents with external systems and data sources',
    'aiDelivery.challenge1': 'Balancing standardization with flexibility — skill-packs need to work across different project types',
    'aiDelivery.challenge2': 'Ensuring AI reliability — structured contexts reduce hallucinations and improve output quality',
    'aiDelivery.challenge3': 'Scaling practices — successful patterns need to transfer across teams without losing effectiveness',
    'aiDelivery.challenge4': 'Measuring impact — quantifying AI contribution to delivery speed and quality',
    'aiDelivery.result1': '30-40% acceleration of "idea → feature implementation" cycle',
    'aiDelivery.result2': '3x reduction in incident localization and resolution time',
    'aiDelivery.result3': 'Standardized AI practices adopted by multiple teams',
    'aiDelivery.result4': 'AI Harness infrastructure enabling reliable autonomous agent behavior',
    'aiDelivery.result5': 'Task decomposition quality improved through AI-assisted creation with human review',
    'achievements.title': 'Achievements',
    'achievements.subtitle': 'Impact',
    'achievements.optimization.label': 'Resource Optimization',
    'achievements.optimization.description': 'Time and resource savings through system automation',
    'achievements.generation.label': 'Faster Generation',
    'achievements.generation.description': 'Document generation speed improvement',
    'achievements.broker.label': 'Broker Interaction',
    'achievements.broker.description': 'Faster broker integration processing',
    'achievements.cycle.label': 'Faster Cycle',
    'achievements.cycle.description': 'Idea to feature delivery acceleration',
    'achievements.platform.label': 'AI Platform',
    'achievements.platform.description': 'Designed and built AI Code Knowledge Platform — a full-stack system for automated code knowledge extraction and documentation generation.',
    'achievements.patent.label': 'Patent',
    'achievements.patent.description': 'Registered patent for automated legal analysis system',
    'techStack.title': 'Technology Map',
    'techStack.subtitle': 'Technical Stack',
    'techStack.backend': 'Backend / Data',
    'techStack.integration': 'Integration',
    'techStack.frontend': 'Frontend',
    'techStack.infrastructure': 'Infrastructure',
    'techStack.ai': 'AI',
    'techStack.tools': 'Analyst Tools',
    'architecture.title': 'How I Think',
    'architecture.subtitle': 'From Problem to Result',
    'architecture.description': "I don't just document requirements — I work across the full spectrum from business problem understanding to architecture design and implementation.",
    'architecture.step1': 'Business Problem',
    'architecture.step2': 'Business Process',
    'architecture.step3': 'Requirements',
    'architecture.step4': 'System Context',
    'architecture.step5': 'Architecture',
    'architecture.step6': 'API / Data',
    'architecture.step7': 'Implementation',
    'architecture.step8': 'Automation / AI',
    'architecture.step9': 'Result',
    'aiResearch.title': 'AI Engineering & Research',
    'aiResearch.subtitle': 'System Analysis + Architecture + AI',
    'aiResearch.description': 'I research AI technologies and build production-oriented AI systems with them. My applied work includes designing and implementing AI Code Knowledge Platform — a full-stack platform for automated code knowledge extraction, graph-based analysis and documentation generation.',
    'aiResearch.llm.title': 'LLM & RAG Systems',
    'aiResearch.llm.description': 'Applying large language models with retrieval-augmented generation for code understanding, documentation and system analysis workflows.',
    'aiResearch.graph.title': 'Graph RAG & Code Graph',
    'aiResearch.graph.description': 'Exploring graph-based models for code analysis — transforming codebases into knowledge graphs for dependency analysis, context search and architecture understanding.',
    'aiResearch.semantic.title': 'Semantic Code Search',
    'aiResearch.semantic.description': 'Building systems that understand code semantically — enabling natural language queries over codebases, documentation and architectural decisions.',
    'aiResearch.agents.title': 'AI Agents & MCP',
    'aiResearch.agents.description': 'Developing AI agent architectures with Model Context Protocol for automated system analysis, requirement generation and technical documentation.',
    'aiResearch.analysis.title': 'AI-assisted Analysis',
    'aiResearch.analysis.description': 'Using AI to accelerate the analyst workflow itself — from requirement gathering and process modeling to architecture documentation and test generation.',
    'aiResearch.aickp.title': 'AI Code Knowledge Platform',
    'aiResearch.aickp.description': 'Designed and built a platform that automatically extracts knowledge from codebases and generates documentation. Used by analysts, engineers, support teams, testers and managers for system understanding and onboarding.',
    'aiResearch.mcpPlatform.title': 'Analyst Skill-packs & AI Agents',
    'aiResearch.mcpPlatform.description': 'Created standardized skill-packs — sets of prompts, context templates and rules for using AI tools in analytics workflows. Built agent configurations for requirements analysis, code review and documentation generation.',
    'aiResearch.mcp.title': 'MCP Servers & Integrations',
    'aiResearch.mcp.description': 'Built and operate MCP (Model Context Protocol) servers for AI agent integration with enterprise systems — enabling agents to access code, documentation, project management tools and communication platforms.',
    'footer.title': "Let's work together",
    'footer.description': 'Open to senior system analyst, solution architecture and AI-focused engineering roles.',
    'footer.rights': 'All rights reserved',
    'footer.builtWith': 'Built with',
    'theme.toggle': 'Toggle theme',
    'language.toggle': 'Toggle language',
  },
  ru: {
    'nav.about': 'Обо мне',
    'nav.experience': 'Опыт',
    'nav.projects': 'Проекты',
    'nav.achievements': 'Достижения',
    'nav.techStack': 'Технологии',
    'nav.architecture': 'Архитектура',
    'nav.aiResearch': 'AI исследования',
    'nav.contact': 'Контакты',
    'hero.title': 'Системы и AI',
    'hero.subtitle': 'Системный аналитик / Системы и AI',
    'hero.name': 'Мансур Какушкин',
    'hero.description': 'Проектирую сложные системы, интеграции и AI-решения — от бизнес-задачи до архитектуры и реализации.',
    'hero.downloadCV': 'Скачать резюме',
    'hero.contactMe': 'Связаться',
    'hero.viewExperience': 'Посмотреть опыт',
    'hero.selectedProjects': 'Избранные проекты',
    'hero.scrollExplore': 'Листайте дальше',
    'about.title': 'Обо мне',
    'about.subtitle': 'Связываю бизнес-требования, системную архитектуру, данные, интеграции и реализацию.',
    'about.description1': 'Системный аналитик с 7+ годами опыта проектирования сложных информационных систем, интеграций и автоматизации для крупных предприятий, включая X5 и Сбер.',
    'about.description2': 'Мой подход выходит за рамки сбора требований и черчения диаграмм. Я работаю во всем спектре — от понимания бизнес-процессов и ограничений до проектирования системной архитектуры, API, структур данных и рабочих процессов реализации.',
    'about.description3': 'Активно применяю AI и автоматизацию в самой инженерной работе — использую LLM, RAG, Graph RAG и графы знаний для ускорения системного анализа, понимания кода и документации. Также самостоятельно проектирую и реализую AI-системы — включая AI Code Knowledge Platform, full-stack платформу для автоматического извлечения знаний из кода, графового анализа и AI-генерации документации.',
    'about.rolesTitle': 'Работаю на стыке:',
    'about.roles': 'Системный анализ,Бизнес-анализ,Архитектура решений,Архитектура интеграций,Проектирование API,Данные,Автоматизация,AI / LLM / RAG,Разработка ПО',
    'experience.title': 'Опыт работы',
    'experience.subtitle': 'Карьерный путь',
    'experience.x5tech.company': 'X5 Tech',
    'experience.x5tech.senior.role': 'Старший системный аналитик',
    'experience.x5tech.senior.period': 'Сентябрь 2025 — настоящее время (1 год)',
    'experience.x5tech.senior.location': 'Москва / Удалённо',
    'experience.x5tech.senior.highlight1': 'Инициировал и реализовал внедрение AI-инструментов в процесс разработки и анализа требований, изменив подход к delivery-флоу внутри команды.',
    'experience.x5tech.senior.highlight2': 'Оцифровал ключевые сервисы и привёл всю проектную документацию к единому структурированному формату; разработал шаблоны, референсы и правила их использования.',
    'experience.x5tech.senior.highlight3': 'Перестроил процесс декомпозиции задач: формирование задач с использованием AI и передача их в разработку с поддержкой AI-инструментов со стороны разработчиков.',
    'experience.x5tech.senior.highlight4': 'Добился ускорения цикла «идея → реализация фичи» на 30–40% за счёт оптимизации подготовки и уточнения задач.',
    'experience.x5tech.senior.highlight5': 'Сократил время локализации и устранения инцидентов в production примерно в 3 раза за счёт улучшения структурирования контекста и автоматизации анализа.',
    'experience.x5tech.senior.highlight6': 'Масштабировал подход на другие команды, проводил обучение и внедрение AI-практик в рамках кросс-командного взаимодействия.',
    'experience.x5tech.senior.highlight7': 'Спроектировал и реализовал AI Code Knowledge Platform — full-stack систему для автоматического извлечения знаний из кода с использованием Graph RAG, AI-агентов и MCP, генерирующую доменную, БД, архитектурную и функциональную документацию из исходного кода.',
    'experience.x5tech.analyst.role': 'Системный аналитик',
    'experience.x5tech.analyst.period': 'Октябрь 2023 — Август 2025 (1 год 11 месяцев)',
    'experience.x5tech.analyst.location': 'Москва / Удалённо',
    'experience.x5tech.analyst.highlight1': 'В рамках проекта «Налоговый мониторинг» анализировал и реализовывал требования ФНС для API-интеграций внутри группы компаний (9 юридических лиц).',
    'experience.x5tech.analyst.highlight2': 'Проектировал микросервисную архитектуру платформы, прорабатывал интеграции с SAP и внешними системами, определял архитектуру взаимодействия внутренних сервисов и структуру БД.',
    'experience.x5tech.analyst.highlight3': 'Реализовал schema-driven подход: полуавтоматически формировал JSON Schema из XSD, спроектировал механизм генерации экранных форм из JSON-схем, которые автоматически строятся под определённую версию XSD — благодаря чему аналитик может самостоятельно загружать обновлённые схемы и формы без участия разработчиков.',
    'experience.x5tech.analyst.highlight4': 'Выполнял функции системного и бизнес-аналитика: сбор и проработка требований, постановка задач разработчикам, приоритизация и контроль реализации.',
    'experience.x5tech.analyst.highlight5': 'Создавал дашборды для мониторинга системы в Grafana и реализовывал логику алертов для отслеживания состояния платформы в production.',
    'experience.aiharness.company': 'AI Harness Engineering',
    'experience.aiharness.role': 'AI Harness инженер / Системный аналитик',
    'experience.aiharness.period': '2024 — настоящее время',
    'experience.aiharness.location': 'Москва / Удалённо',
    'experience.aiharness.highlight1': 'Спроектировал и реализовал AI Code Knowledge Platform — end-to-end платформу, извлекающую верифицируемые знания из исходного кода через структурные графы кода, AI-агентов и семантические базы знаний.',
    'experience.aiharness.highlight2': 'Выстроил Graph RAG-пайплайн: GitLab → Code Graph → Graph MCP → AI Agent → Documentation с автоматической генерацией доменной, БД, архитектурной и функциональной документации.',
    'experience.aiharness.highlight3': 'Создал AI chat workspace с мульти-проектными MCP-интеграциями (Confluence, Figma, Kaiten, Exchange), отслеживанием выполнения субагентов и мониторингом токенов/стоимости.',
    'experience.aiharness.highlight4': 'Реализовал оркестрацию задач, автосинхронизацию с GitLab, управление Docker-based runtime для контейнеров Memgraph, Graph MCP и AI-агентов.',
    'experience.extrum.company': 'Extrum',
    'experience.extrum.role': 'Бизнес / Системный аналитик',
    'experience.extrum.period': 'Ноябрь 2022 — Сентябрь 2023 (11 месяцев)',
    'experience.extrum.location': 'Москва',
    'experience.extrum.highlight1': 'Формирование и согласование проектной документации с Заказчиками.',
    'experience.extrum.highlight2': 'Проработка и согласование внутренней архитектуры сервиса, сроков, стоимости, интеграционных взаимодействий и дизайна.',
    'experience.extrum.highlight3': 'Тестирование готового функционала, заведение задач на доработку.',
    'experience.extrum.highlight4': 'Создание технической документации, контроль разработки и тестирование. Программы реализованы в кратчайшие сроки и оптимизировали работу бизнес-подразделений в несколько раз.',
    'experience.extrum.highlight5': 'Формирование команды разработчиков и дизайнера, управление беклогом, приоритетами, сроками и контроль исполнения.',
    'experience.smartauto.company': 'ООО Умная Автоматизация',
    'experience.smartauto.role': 'Системный аналитик',
    'experience.smartauto.period': 'Ноябрь 2022 — Апрель 2023 (6 месяцев)',
    'experience.smartauto.location': 'Москва',
    'experience.smartauto.highlight1': 'Создание и согласование проектной документации по внедрению сервиса. Сервис успешно внедрён и интегрирован с внутренними сервисами у 3 Заказчиков из сегмента крупного бизнеса.',
    'experience.smartauto.highlight2': 'Формирование выгрузок из БД сервиса для аналитики и отчётности по работе системы.',
    'experience.smartauto.highlight3': 'Выявлено 15 критических дефектов, блокирующих работу; описание сценариев, приоритезация и устранение.',
    'experience.smartauto.highlight4': 'Подготовка технической документации по расширению функционала и тестирование. Добавлены 4 фичи, упростившие работу пользователям и администраторам.',
    'experience.smartauto.highlight5': 'Самостоятельно выполнял новые релизы сервиса во внутреннем контуре Заказчиков.',
    'experience.sber.role': 'Системный аналитик',
    'experience.sber.period': 'Декабрь 2018 — Октябрь 2022 (3 года 11 месяцев)',
    'experience.sber.location': 'Москва',
    'experience.sber.highlight1': 'Участие в разработке языка DSL на базе Python как инструмента due diligence в корпоративном кредитовании.',
    'experience.sber.highlight2': 'Создание внутреннего аналитического сервиса для команды аудиторов для хранения данных и загрузки информации.',
    'experience.sber.highlight3': 'Выявление технических/логических ошибок и формирование предложений по улучшению работы сервиса Робот юрист.',
    'experience.sber.highlight4': 'Разработка и техническая поддержка проектов LegalTech, развитие автоматизированного процесса due diligence (исследование AS IS, разработка TO BE процессов).',
    'experience.sber.highlight5': 'При взаимодействии с командой DS участвовал в создании и улучшении до 90% F-меры сервиса для формирования документов на основе ML.',
    'experience.sber.highlight6': 'Управление бэклогом, координация ресурсов команды во время спринта, подготовка к развёртыванию релизов.',
    'projects.title': 'Избранные проекты',
    'projects.subtitle': 'Кейсы',
    'projects.tax.title': 'Система налогового мониторинга',
    'projects.tax.subtitle': 'SAP / ФНС / Микросервисы / PostgreSQL / ClickHouse / Airflow',
    'projects.tax.description': 'Система, интегрированная с SAP и корпоративными системами для мониторинга ФНС. Микросервисная архитектура для 40+ пользователей в 9 юридических лицах.',
    'projects.tax.metric1': 'Оптимизация ресурсов в 5 раз',
    'projects.tax.metric2': '9 юридических лиц',
    'projects.tax.metric3': '40+ пользователей',
    'projects.schema.title': 'Автоматизация на основе схем',
    'projects.schema.subtitle': 'XSD → JSON Schema → Python',
    'projects.schema.description': 'Автоматизированный конвейер обработки схем документов, преобразующий XSD-схемы в JSON Schema и генерирующий скрипты обработки — снижение ручной работы аналитика.',
    'projects.schema.metric1': 'Обработка в 5 раз быстрее',
    'projects.schema.metric2': 'Снижение ручной работы',
    'projects.aiDelivery.title': 'AI Delivery Transformation',
    'projects.aiDelivery.subtitle': 'Skill-packs / Контекст / AI Harness',
    'projects.aiDelivery.description': 'Полная AI-трансформация процессов delivery в X5 Tech. Создание стандартизированных skill-packs для AI-инструментов, реструктуризация декомпозиции задач, построение AI Harness инфраструктуры — ускорение цикла «идея → фича» на 30–40%.',
    'projects.aiDelivery.metric1': 'Delivery быстрее на 30–40%',
    'projects.aiDelivery.metric2': 'Инциденты решаются в 3 раза быстрее',
    'projects.aiDelivery.metric3': 'Масштабировано на несколько команд',
    'projects.ai.title': 'AI Code Knowledge Platform',
    'projects.ai.subtitle': 'Graph RAG / AI Agents / MCP / Knowledge Graph',
    'projects.ai.description': 'Спроектировал и реализовал end-to-end платформу для автоматического извлечения знаний из исходного кода. Преобразует репозитории в графы знаний, генерирует документацию через AI-агентов и предоставляет AI-чат с мульти-проектным контекстом и MCP-интеграциями.',
    'projects.ai.metric1': 'Full-stack платформа',
    'projects.ai.metric2': '4 пайплайна документации',
    'projects.ai.metric3': 'AI чат + MCP',
    'projects.viewCaseStudy': 'Посмотреть кейс',
    'casestudy.problem': 'Проблема',
    'casestudy.context': 'Контекст',
    'casestudy.myRole': 'Моя роль',
    'casestudy.architecture': 'Архитектура',
    'casestudy.solution': 'Техническое решение',
    'casestudy.challenges': 'Сложности',
    'casestudy.result': 'Результат',
    'casestudy.technologies': 'Технологии',
    'casestudy.back': 'Назад к проектам',
    'casestudy.label': 'Кейс',
    'tax.problem': 'Крупной группе предприятий требовалась новая автоматизированная система налогового мониторинга — АИС Налог 3 — для замены ручного процесса отчётности перед ФНС. Существующий процесс включал извлечение данных из множества корпоративных систем, включая SAP, что было трудоёмким и подверженным ошибкам. Решение разрабатывалось с упором на автоматизацию работы пользователей в масштабе 9 юридических лиц.',
    'tax.context': 'Система должна была обслуживать 40+ пользователей в группе из 9 юридических лиц. Источниками данных выступали SAP ERP и другие корпоративные системы. Архитектура требовала микросервисов для обработки различных аспектов извлечения данных, валидации и отчётности.',
    'tax.role1': 'Системный анализ и сбор требований от бизнес-стейкхолдеров',
    'tax.role2': 'Проектирование интеграционной архитектуры между SAP, PostgreSQL, ClickHouse и внутренними системами',
    'tax.role3': 'Определение API-контрактов и структур данных для микросервисного взаимодействия',
    'tax.role4': 'Техническая документация и записи архитектурных решений',
    'tax.role5': 'Координация между бизнесом, разработкой и эксплуатацией',
    'tax.arch': 'Микросервисная архитектура с выделенными сервисами для извлечения, трансформации, валидации данных и отчётности. Интеграционный слой SAP для синхронизации данных. PostgreSQL для транзакционных данных, ClickHouse для аналитических запросов и отчётности. Airflow для оркестрации пайплайнов данных.',
    'tax.solution1': 'REST API слой для межсервисного взаимодействия с чётко определёнными контрактами',
    'tax.solution2': 'ETL-пайплайны под управлением Airflow для извлечения и трансформации данных',
    'tax.solution3': 'Schema-driven валидация данных для обеспечения соответствия требованиям ФНС',
    'tax.solution4': 'Слой кеширования для часто запрашиваемых справочных данных',
    'tax.solution5': 'Мониторинг и алертинг для состояния пайплайнов данных',
    'tax.challenge1': 'Сложные структуры данных в 9 различных юридических лицах с разными конфигурациями',
    'tax.challenge2': 'Интеграция с SAP, требующая глубокого понимания корпоративных моделей данных',
    'tax.challenge3': 'Жёсткие требования ФНС к соответствию с нулевой толерантностью к ошибкам данных',
    'tax.challenge4': 'Требования к производительности для больших объёмов данных в аналитических запросах',
    'tax.result1': '5-кратная оптимизация по времени и использованию ресурсов за счёт автоматизации',
    'tax.result2': 'Успешное обслуживание 40+ пользователей в 9 юридических лицах',
    'tax.result3': 'Устранено ручное извлечение данных и ошибки валидации',
    'tax.result4': 'Сокращено время генерации отчётов с дней до часов',
    'schema.problem': 'Ранее для каждой XSD-схемы разработчикам приходилось вручную создавать экранные формы — это требовало участия разработчиков при каждой новой версии схемы. Это создавало узкое место: любое изменение XSD означало работу разработчиков по обновлению соответствующих форм.',
    'schema.context': 'Спроектирован универсальный механизм: JSON Schema полуавтоматически генерируется из XSD и передаётся на фронтенд, который автоматически рисует экранные формы под конкретную версию XSD. Теперь при изменении XSD аналитику достаточно обновить JSON Schema — экранные формы адаптируются автоматически без участия разработчиков.',
    'schema.role1': 'Выявил возможность автоматизации в процессе обработки схем',
    'schema.role2': 'Спроектировал конвейер трансформации XSD → JSON Schema → Python',
    'schema.role3': 'Реализовал Python-скрипты для автоматической конвертации схем и генерации кода',
    'schema.role4': 'Проверил точность результатов относительно ручной обработки',
    'schema.arch': 'Архитектура конвейера: XSD источник → слой парсинга → генерация JSON Schema → генерация Python-скриптов → валидация → выходные артефакты. Каждый этап модульный и может быть расширен для новых типов схем или форматов вывода.',
    'schema.solution1': 'Парсер XSD на Python, извлекающий определения типов, ограничения и связи',
    'schema.solution2': 'Полуавтоматическая генерация JSON Schema из XSD с учётом бизнес-логики',
    'schema.solution3': 'Бэкенд использует библиотеку для конвертации JSON → XML. JSON Schema передаётся на фронтенд, который автоматически рисует поля формы и собирает данные в FormData',
    'schema.solution4': 'Аналитику достаточно загружать обновлённые JSON Schema при изменении XSD — разработчики не участвуют в процессе',
    'schema.challenge1': 'Сложные возможности XSD, включая пространства имён, наследование и пользовательские типы',
    'schema.challenge2': 'Поддержание точности при автоматических трансформациях',
    'schema.challenge3': 'Обработка граничных случаев в определениях схем без вмешательства человека',
    'schema.result1': '5-кратное ускорение обработки схем за счёт автоматизации',
    'schema.result2': 'Значительное сокращение ручной работы аналитиков и разработчиков',
    'schema.result3': 'Ускорение реагирования на запросы изменений схем',
    'schema.result4': 'Снижение ошибок при переводе из схемы в код',
    'schema.result5': 'Разработка полностью исключена из процесса — всё работает автоматически',
    'ai.problem': 'Системные аналитики и инженеры тратят значительное время на понимание существующих кодовых баз — отслеживание зависимостей, поиск контекста и ручное написание документации. Знания о системах хранятся в головах людей и разрозненных документах, что замедляет онбординг и делает анализ подверженным ошибкам.',
    'ai.context': 'Современные корпоративные системы имеют глубокие цепочки зависимостей и распределённые архитектуры. Цель состояла в создании платформы, которая автоматически извлекает структурированные знания из исходного кода и превращает их в запрашиваемую документацию — чтобы аналитики, инженеры, поддержка, тестировщики и менеджеры могли понимать системы быстрее, не читая тысячи строк кода. Платформа также служит инструментом онбординга для новых сотрудников.',
    'ai.role1': 'Спроектировал концепт продукта и определил возможности для разных ролей: аналитики, инженеры, поддержка, тестировщики и менеджеры',
    'ai.role2': 'Собрал всю систему самостоятельно — от архитектуры до готового продукта, готового к использованию командами',
    'ai.role3': 'Реализовал автоматическую генерацию документации, покрывающей доменные модели, схемы БД, архитектуру и API',
    'ai.role4': 'Создал интерактивное AI-рабочее пространство, где аналитики могут задавать вопросы о кодовых базах на естественном языке',
    'ai.role5': 'Спроектировал интеграционный слой, связывающий платформу с существующими корпоративными инструментами',
    'ai.arch': 'Платформа подключается к репозиториям исходного кода, автоматически выстраивает структурированное понимание кодовой базы и использует AI-агентов для генерации документации, ответов на вопросы и извлечения знаний. Всё работает через единый веб-интерфейс без ручной настройки под каждый репозиторий.',
    'ai.solution1': 'Автоматический анализ кодовой базы: графы зависимостей, связи модулей и архитектурные паттерны без ручного труда',
    'ai.solution2': 'Четыре пайплайна документации: доменная, БД, архитектурная и функциональная — генерируются AI-агентами',
    'ai.solution3': 'AI-чат с полным контекстом кодовой базы: вопросы на естественном языке, ответы на основе реального кода',
    'ai.solution4': 'База знаний: документация индексируется семантически, AI находит релевантный контекст по всем проектам',
    'ai.solution5': 'Корпоративные интеграции: подключение к Confluence, Figma, Kaiten и почте для единого рабочего процесса',
    'ai.challenge1': 'Обеспечение работы с крупными реальными репозиториями без ручной конфигурации',
    'ai.challenge2': 'Точность и полезность AI-документации — не просто правдоподобный текст, а действительно полезное содержание',
    'ai.challenge3': 'Поддержание актуальности знаний при изменениях в коде — не разовый экспорт, а живая система',
    'ai.challenge4': 'Создание продукта, которым аналитики действительно захотят пользоваться, а не ещё одного внутреннего инструмента',
    'ai.result1': 'Full-stack продукт с автоматической генерацией документации, AI-чатом и базой знаний',
    'ai.result2': 'Команды могут понять новую кодовую базу за часы вместо дней — аналитики, поддержка, тестировщики и новые сотрудники',
    'ai.result3': 'Документация остаётся актуальной через автоматическую синхронизацию с кодовыми репозиториями',
    'ai.result4': 'Готова к развёртыванию и использованию командами разработки, аналитики, поддержки и менеджмента',
    'aiDelivery.problem': 'Команды X5 Tech сталкивались с проблемами в эффективном внедрении AI-инструментов. Каждая команда использовала AI по-разному, контекст был плохо структурирован, а декомпозиция задач оставалась ручной. Это создавало непоследовательное качество и медленные циклы delivery.',
    'aiDelivery.context': 'Крупное предприятие с несколькими командами разработки, работающими над веб-приложениями различных бизнес-доменов. Необходимость стандартизировать внедрение AI, сохраняя гибкость для разных контекстов команд и типов проектов.',
    'aiDelivery.role1': 'Создание стандартизированных skill-packs — наборов контекстов, правил и шаблонов для использования AI-инструментов в аналитике и разработке',
    'aiDelivery.role2': 'Реструктуризация процесса декомпозиции задач: AI-ассистированное создание задач со структурированными промптами и передача в разработку',
    'aiDelivery.role3': 'Построение AI Harness инфраструктуры — программный слой вокруг LLM, обеспечивающий оркестрацию инструментов, память и управление контекстом',
    'aiDelivery.role4': 'Внедрение паттернов структурирования контекста для надёжного поведения AI-агентов',
    'aiDelivery.role5': 'Обучение и масштабирование AI-практик на несколько команд через воркшопы и документацию',
    'aiDelivery.arch': 'Skill-packs → Шаблоны контекста → AI-инструменты → Harness-слой → Development-флоу. Система обеспечивает стандартизированные паттерны взаимодействия с AI со структурированными контекстами, обеспечивая согласованное качество между командами с возможностью кастомизации под проект.',
    'aiDelivery.solution1': 'Skill-packs: курированные наборы промптов, правил и шаблонов контекста для конкретных задач (анализ требований, код-ревью, документация)',
    'aiDelivery.solution2': 'AI Harness: программная инфраструктура вокруг LLM, обеспечивающая управление инструментами, контроль вывода и мониторинг результатов',
    'aiDelivery.solution3': 'Структурированная декомпозиция задач: AI генерирует разбивку задач с критериями приёмки, разработчики проверяют и реализуют с поддержкой AI',
    'aiDelivery.solution4': 'Система управления контекстом: поддержание релевантного контекста в разговорах и взаимодействиях с инструментами',
    'aiDelivery.solution5': 'Интеграция MCP (Model Context Protocol) для подключения AI-агентов к внешним системам и источникам данных',
    'aiDelivery.challenge1': 'Баланс между стандартизацией и гибкостью — skill-packs должны работать для разных типов проектов',
    'aiDelivery.challenge2': 'Обеспечение надёжности AI — структурированные контексты снижают галлюцинации и улучшают качество вывода',
    'aiDelivery.challenge3': 'Масштабирование практик — успешные паттерны должны переноситься между командами без потери эффективности',
    'aiDelivery.challenge4': 'Измерение влияния — квантификация вклада AI в скорость и качество delivery',
    'aiDelivery.result1': '30–40% ускорение цикла «идея → реализация фичи»',
    'aiDelivery.result2': '3-кратное сокращение времени локализации и решения инцидентов',
    'aiDelivery.result3': 'Стандартизированные AI-практики, внедрённые в нескольких командах',
    'aiDelivery.result4': 'AI Harness инфраструктура, обеспечивающая надёжное поведение автономных агентов',
    'aiDelivery.result5': 'Улучшение качества декомпозиции задач через AI-ассистированное создание с человеческим контролем',
    'achievements.title': 'Достижения',
    'achievements.subtitle': 'Импакт',
    'achievements.optimization.label': 'Оптимизация ресурсов',
    'achievements.optimization.description': 'Экономия времени и ресурсов через автоматизацию систем',
    'achievements.generation.label': 'Ускорение генерации',
    'achievements.generation.description': 'Улучшение скорости генерации документов',
    'achievements.broker.label': 'Взаимодействие с брокерами',
    'achievements.broker.description': 'Ускорение обработки интеграций с брокерами',
    'achievements.cycle.label': 'Ускорение цикла',
    'achievements.cycle.description': 'Ускорение доставки от идеи до фичи',
    'achievements.platform.label': 'AI-платформа',
    'achievements.platform.description': 'Спроектировал и реализовал AI Code Knowledge Platform — full-stack систему для автоматического извлечения знаний из кода и генерации документации.',
    'achievements.patent.label': 'Патент',
    'achievements.patent.description': 'Зарегистрированный патент на автоматизированную систему юридического анализа',
    'techStack.title': 'Карта технологий',
    'techStack.subtitle': 'Технический стек',
    'techStack.backend': 'Бэкенд / Данные',
    'techStack.integration': 'Интеграции',
    'techStack.frontend': 'Фронтенд',
    'techStack.infrastructure': 'Инфраструктура',
    'techStack.ai': 'AI',
    'techStack.tools': 'Инструменты аналитика',
    'architecture.title': 'Как я мыслю',
    'architecture.subtitle': 'От проблемы к результату',
    'architecture.description': 'Я не просто документирую требования — я работаю во всем спектре: от понимания бизнес-задачи до проектирования архитектуры и реализации.',
    'architecture.step1': 'Бизнес-задача',
    'architecture.step2': 'Бизнес-процесс',
    'architecture.step3': 'Требования',
    'architecture.step4': 'Системный контекст',
    'architecture.step5': 'Архитектура',
    'architecture.step6': 'API / Данные',
    'architecture.step7': 'Реализация',
    'architecture.step8': 'Автоматизация / AI',
    'architecture.step9': 'Результат',
    'aiResearch.title': 'AI-инжиниринг и исследования',
    'aiResearch.subtitle': 'Системный анализ + Архитектура + AI',
    'aiResearch.description': 'Исследую AI-технологии и строю на их основе production-ориентированные AI-системы. Моя прикладная работа включает проектирование и реализацию AI Code Knowledge Platform — full-stack системы для автоматического извлечения знаний из кода, графового анализа и генерации документации.',
    'aiResearch.llm.title': 'LLM и RAG системы',
    'aiResearch.llm.description': 'Применение больших языковых моделей с генерацией с дополнительным поиском для понимания кода, документации и рабочих процессов системного анализа.',
    'aiResearch.graph.title': 'Graph RAG и Code Graph',
    'aiResearch.graph.description': 'Исследование графовых моделей для анализа кода — преобразование кодовых баз в графы знаний для анализа зависимостей, контекстного поиска и понимания архитектуры.',
    'aiResearch.semantic.title': 'Семантический поиск кода',
    'aiResearch.semantic.description': 'Создание систем, которые понимают код семантически — обеспечивая запросы на естественном языке по кодовым базам, документации и архитектурным решениям.',
    'aiResearch.agents.title': 'AI агенты и MCP',
    'aiResearch.agents.description': 'Разработка архитектур AI-агентов с Model Context Protocol для автоматизированного системного анализа, генерации требований и технической документации.',
    'aiResearch.analysis.title': 'AI-ассистированный анализ',
    'aiResearch.analysis.description': 'Использование AI для ускорения самого рабочего процесса аналитика — от сбора требований и моделирования процессов до документирования архитектуры и генерации тестов.',
    'aiResearch.aickp.title': 'AI Code Knowledge Platform',
    'aiResearch.aickp.description': 'Спроектировал и реализовал платформу, автоматически извлекающую знания из кодовых баз и генерирующую документацию. Используется аналитиками, инженерами, поддержкой, тестировщиками и менеджерами для понимания систем и онбординга.',
    'aiResearch.mcpPlatform.title': 'Skill-packs и AI-агенты для аналитиков',
    'aiResearch.mcpPlatform.description': 'Создание стандартизированных skill-packs — наборов промптов, шаблонов контекста и правил для использования AI-инструментов в аналитических процессах. Настройка агентов для анализа требований, код-ревью и генерации документации.',
    'aiResearch.mcp.title': 'MCP-серверы и интеграции',
    'aiResearch.mcp.description': 'Создание и эксплуатация MCP-серверов (Model Context Protocol) для интеграции AI-агентов с корпоративными системами — доступ агентов к коду, документации, инструментам управления проектами и коммуникационным платформам.',
    'footer.title': 'Давайте работать вместе',
    'footer.description': 'Открыт для позиций системного аналитика, архитектора решений и AI-инженера.',
    'footer.rights': 'Все права защищены',
    'footer.builtWith': 'Создано с помощью',
    'theme.toggle': 'Переключить тему',
    'language.toggle': 'Переключить язык',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
