'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.about': 'About',
    'nav.experience': 'Experience',
    'nav.projects': 'Projects',
    'nav.architecture': 'Architecture',
    'nav.aiResearch': 'AI Research',
    'nav.contact': 'Contact',
    'hero.title': 'Systems & AI',
    'hero.subtitle': 'Senior System Analyst / Systems & AI',
    'hero.name': 'Mansur Kakushkin',
    'hero.description': 'I design complex systems, integrations and AI-powered workflows — from business problem to architecture and implementation.',
    'hero.downloadCV': 'Download CV',
    'hero.contactMe': 'Contact Me',
    'hero.viewExperience': 'View Experience',
    'hero.selectedProjects': 'Selected Projects',
    'hero.scrollExplore': 'Scroll to explore',
    'about.title': 'About',
    'about.subtitle': 'I design enterprise systems across the full cycle — from business problem to architecture, APIs, data, integrations and AI automation.',
    'about.description1': 'Senior Systems Analyst with 7+ years in enterprise technology. I have worked at X5 and Sber — designing complex information systems, integrations and automation at scale.',
    'about.description2': 'I own problems end-to-end: translating business logic into system requirements, designing architecture, defining APIs and data structures, building integrations, and following through to production. My work covers the full cycle — business process → requirements → system design → implementation → result.',
    'about.description3': 'I also build AI-powered systems and apply LLM, RAG, Graph RAG, knowledge graphs and AI agents to engineering work. I designed and built AI Code Knowledge Platform — a full-stack platform for automated code knowledge extraction, graph-based analysis and AI-generated documentation. I also contributed to a product that received patent RU2732071C1 for automated legal analysis.',
    'about.description4': 'Currently looking for Senior Systems Analyst, Solution Architect or AI-focused engineering roles where I can work on complex systems, integrations and architecture at scale.',
    'about.rolesTitle': 'I work at the intersection of:',
    'about.roles': 'System Architecture,Integration Architecture,API Design,Data Pipelines,AI / LLM / RAG,Knowledge Graphs,MCP / AI Agents,Software Engineering',
    'about.impactTitle': 'Selected Impact',
    'about.impact1Label': 'Resource Optimization',
    'about.impact1Value': '5x',
    'about.impact1Desc': 'through system automation',
    'about.impact2Label': 'Faster Delivery',
    'about.impact2Value': '30–40%',
    'about.impact2Desc': 'idea-to-feature cycle reduction',
    'about.impact3Label': 'Incident Resolution',
    'about.impact3Value': '~3x',
    'about.impact3Desc': 'faster in production',
    'about.impact4Label': 'Patent',
    'about.impact4Value': 'RU2732071C1',
    'about.impact4Desc': 'participant in automated legal analysis system',
    'experience.title': 'Experience',
    'experience.subtitle': 'Career Path',
    'experience.x5tech.company': 'X5 Tech',
    'experience.x5tech.senior.role': 'Senior System Analyst',
    'experience.x5tech.senior.period': 'Sep 2025 — Present (1 year)',
    'experience.x5tech.senior.location': 'Moscow / Remote',
    'experience.x5tech.senior.highlight1': 'Coordinate delivery across 2 project teams and 1 product team — performing project coordination, defining priorities and directing day-to-day work across developers, analysts and QA.',
    'experience.x5tech.senior.highlight2': 'Redesigned the requirements-to-development workflow around AI-assisted specifications, Git-based documentation, automated test generation and AI-powered code reviews — reducing idea-to-feature delivery time by 30–40% and enabling the team to handle a workload that would have required ~1.5× the original headcount.',
    'experience.x5tech.senior.highlight3': 'Introduced AI-assisted incident investigation with structured technical context and MCP integrations with task trackers, reducing production incident resolution from 2–3 days to under 1 day through faster root-cause analysis.',
    'experience.x5tech.senior.highlight4': 'Conceived, designed and built AI Code Knowledge Platform — a full-stack system (Python, React, MCP, Memgraph) that automatically extracts knowledge from codebases, generates documentation and provides AI chat over system context. Scaled from personal workflow → 5 analysts → multiple teams. Now in user testing across analysts, developers, support and QA.',
    'experience.x5tech.senior.highlight5': 'Embedded AI across the delivery pipeline — requirements engineering, documentation generation, test case creation, API specification review and automated code analysis — establishing AI as a core tool rather than an isolated experiment.',
    'experience.x5tech.senior.highlight6': 'Brought all project documentation to a unified structured format with templates, references and usage rules, enabling consistent onboarding and cross-team handoffs.',
    'experience.x5tech.senior.highlight7': 'Scaled AI practices across teams through workshops, training and cross-team collaboration, expanding adoption beyond individual projects.',
    'experience.x5tech.analyst.role': 'System Analyst',
    'experience.x5tech.analyst.period': 'Oct 2023 — Aug 2025 (1 year 11 months)',
    'experience.x5tech.analyst.location': 'Moscow / Remote',
    'experience.x5tech.analyst.highlight1': 'Designed architecture for a large-scale tax monitoring platform integrating with ~7 external systems (SAP, FNS, signing/EC services), coordinating integration contracts across business processes and internal services. Solution serves 9 legal entities, 4 internal divisions and 40+ users.',
    'experience.x5tech.analyst.highlight2': 'Designed a schema-driven approach: XSD → JSON Schema → UI generation pipeline, eliminating developer involvement in supporting new schema versions — screen forms now auto-adapt when analysts update the schema.',
    'experience.x5tech.analyst.highlight3': 'Integrated new data sources for automated report generation, reducing manual workload equivalent to approximately 2 FTE.',
    'experience.x5tech.analyst.highlight4': 'Defined API contracts and integration interfaces between SAP, PostgreSQL, ClickHouse and internal services, coordinating requirements across teams.',
    'experience.x5tech.analyst.highlight5': 'Built monitoring dashboards in Grafana and implemented alert logic for production system health tracking.',
    'experience.x5tech.analyst.highlight6': 'Performed system and business analyst functions: requirements gathering, task creation for developers, prioritization and implementation control.',
    'experience.extrum.company': 'Extrum',
    'experience.extrum.role': 'Business / System Analyst',
    'experience.extrum.period': 'Nov 2022 — Sep 2023 (11 months)',
    'experience.extrum.location': 'Astana',
    'experience.extrum.highlight1': 'Collected requirements, wrote technical specifications and coordinated architecture decisions with customers and development teams.',
    'experience.extrum.highlight2': 'Managed backlog, priorities and timelines; assembled the development team and directed deliverables.',
    'experience.extrum.highlight3': 'Tested functionality, identified issues and drove resolution through structured task management.',
    'experience.smartauto.company': 'Smart Automation',
    'experience.smartauto.role': 'System Analyst',
    'experience.smartauto.period': 'Nov 2022 — Apr 2023 (6 months)',
    'experience.smartauto.location': 'Remote',
    'experience.smartauto.highlight1': 'Configured and implemented Smart Automation product for 3 enterprise customers, creating project documentation and coordinating delivery.',
    'experience.smartauto.highlight2': 'Identified 15 critical blocking defects, prioritized and resolved them; added features that improved workflows for users and administrators.',
    'experience.sber.role': 'System Analyst',
    'experience.sber.period': 'Dec 2018 — Oct 2022 (3 years 11 months)',
    'experience.sber.location': 'Moscow',
    'experience.sber.highlight1': 'Co-created an ML-based document generation service achieving 90% F-measure in collaboration with the data science team.',
    'experience.sber.highlight2': 'Developed and maintained LegalTech projects automating due diligence processes in corporate lending.',
    'experience.sber.highlight3': 'Built an internal analytics service for the audit team; developed Python-based DSL tooling for automated due diligence.',
    'projects.title': 'Selected Projects',
    'projects.subtitle': 'Case Studies',
    'projects.tax.title': 'Tax Monitoring System',
    'projects.tax.subtitle': 'SAP / FNS / Microservices / PostgreSQL / ClickHouse / Airflow',
    'projects.tax.description': 'System integrated with SAP and corporate systems for Federal Tax Service monitoring. Microservice architecture serving 40+ users across 9 legal entities.',
    'projects.tax.metric1': '5x resource optimization',
    'projects.tax.metric2': '9 legal entities',
    'projects.tax.metric3': '40+ users',
    'projects.schema.title': 'Schema-driven Automation',
    'projects.schema.subtitle': 'XSD → JSON Schema → Python',
    'projects.schema.description': 'Automated pipeline for document schema processing, transforming XSD schemas into JSON Schema and generating processing scripts — reducing manual analyst work.',
    'projects.schema.metric1': '5x faster processing',
    'projects.schema.metric2': 'Reduced manual work',
    'projects.aiDelivery.title': 'AI Delivery Transformation',
    'projects.aiDelivery.subtitle': 'Skill-packs / Context Structuring / AI Harness',
    'projects.aiDelivery.description': 'End-to-end AI transformation of delivery processes at X5 Tech. Created standardized skill-packs for AI tools, restructured task decomposition workflows, and built AI Harness infrastructure — reducing idea-to-feature cycle by 30-40%.',
    'projects.aiDelivery.metric1': '30-40% faster delivery',
    'projects.aiDelivery.metric2': '3x faster incident resolution',
    'projects.aiDelivery.metric3': 'Scaled to multiple teams',
    'projects.ai.title': 'AI Code Knowledge Platform',
    'projects.ai.subtitle': 'Graph RAG / AI Agents / MCP / Knowledge Graph',
    'projects.ai.description': 'Designed and built an end-to-end platform for automated code knowledge extraction from source code. Transforms repositories into knowledge graphs, generates documentation through AI agents and provides AI chat with multi-project context and MCP integrations.',
    'projects.ai.metric1': 'Full-stack platform',
    'projects.ai.metric2': '4 doc pipelines',
    'projects.ai.metric3': 'AI chat + MCP',
    'projects.viewCaseStudy': 'View Case Study',
    'casestudy.problem': 'Problem',
    'casestudy.context': 'Context',
    'casestudy.myRole': 'My Role',
    'casestudy.architecture': 'Architecture',
    'casestudy.solution': 'Technical Solution',
    'casestudy.challenges': 'Challenges',
    'casestudy.result': 'Result',
    'casestudy.technologies': 'Technologies',
    'casestudy.back': 'Back to Projects',
    'casestudy.label': 'Case Study',
    'tax.problem': 'A large enterprise group required a new automated tax monitoring system — AIS Tax 3 — to replace the manual reporting process to the Federal Tax Service (FNS). The existing workflow involved extracting data from multiple corporate systems including SAP, which was time-consuming and error-prone. The entire solution was designed with a focus on automating user workflows across 9 legal entities.',
    'tax.context': 'The system needed to serve 40+ users across a group of 9 legal entities. Data sources included SAP ERP and other corporate systems. The architecture required microservices to handle different aspects of data processing, validation and reporting independently.',
    'tax.role1': 'System analysis and requirements gathering from business stakeholders',
    'tax.role2': 'Designing integration architecture between SAP, PostgreSQL, ClickHouse and internal systems',
    'tax.role3': 'Defining API contracts and data structures for microservice communication',
    'tax.role4': 'Technical documentation and architecture decision records',
    'tax.role5': 'Coordination between business, development and operations teams',
    'tax.arch': 'Microservice architecture with dedicated services for data extraction, transformation, validation and reporting. SAP integration layer handling data synchronization. PostgreSQL for transactional data, ClickHouse for analytical queries and reporting. Airflow orchestrating data pipelines.',
    'tax.solution1': 'REST API layer for inter-service communication with well-defined contracts',
    'tax.solution2': 'ETL pipelines orchestrated by Airflow for data extraction and transformation',
    'tax.solution3': 'Schema-driven data validation ensuring compliance with FNS requirements',
    'tax.solution4': 'Caching layer for frequently accessed reference data',
    'tax.solution5': 'Monitoring and alerting for data pipeline health',
    'tax.challenge1': 'Complex data structures across 9 different legal entities with varying configurations',
    'tax.challenge2': 'SAP integration requiring deep understanding of enterprise data models',
    'tax.challenge3': 'Strict compliance requirements from FNS with zero tolerance for data errors',
    'tax.challenge4': 'Performance requirements for large data volumes in analytical queries',
    'tax.result1': '5x optimization in time and resource usage through automation',
    'tax.result2': 'Successfully serving 40+ users across 9 legal entities',
    'tax.result3': 'Eliminated manual data extraction and validation errors',
    'tax.result4': 'Reduced report generation time from days to hours',
    'schema.problem': 'Previously, for every XSD schema developers had to manually build screen forms — a process that required involvement for each new schema version. This created a bottleneck: any XSD change meant developer work to update the corresponding forms.',
    'schema.context': 'A universal mechanism was designed: JSON Schema is generated semi-automatically from XSD and sent to the frontend, which automatically renders form fields for that specific XSD version. Now when an XSD changes, the analyst only needs to update the JSON Schema — the screen forms adapt automatically without developer involvement.',
    'schema.role1': 'Identified the automation opportunity in the schema processing workflow',
    'schema.role2': 'Designed the XSD → JSON Schema → Python transformation pipeline',
    'schema.role3': 'Implemented Python scripts for automated schema conversion and code generation',
    'schema.role4': 'Validated output accuracy against manual processing results',
    'schema.arch': 'Pipeline architecture: XSD source → parsing layer → JSON Schema generation → Python script generation → validation → output artifacts. Each stage is modular and can be extended for new schema types or output formats.',
    'schema.solution1': 'Python-based XSD parser extracting type definitions, constraints and relationships',
    'schema.solution2': 'Semi-automated JSON Schema generation from XSD considering business logic',
    'schema.solution3': 'Backend uses a library for JSON → XML conversion. JSON Schema is sent to frontend, which automatically renders form fields and collects data into FormData',
    'schema.solution4': 'Analyst only needs to upload updated JSON Schema when XSD changes — developers are not involved in the process',
    'schema.challenge1': 'Complex XSD features including namespaces, inheritance and custom types',
    'schema.challenge2': 'Maintaining accuracy across automated transformations',
    'schema.challenge3': 'Handling edge cases in schema definitions without human intervention',
    'schema.result1': '5x faster schema processing through automation',
    'schema.result2': 'Significantly reduced manual work for analysts and developers',
    'schema.result3': 'Faster turnaround on schema change requests',
    'schema.result4': 'Reduced errors in schema-to-code translation',
    'schema.result5': 'Development completely removed from the process — everything works automatically',
    'ai.problem': 'System analysts and engineers spend significant time understanding existing codebases — tracing dependencies, finding context and writing documentation manually. Knowledge about systems lives in people\'s heads and scattered documents, making onboarding slow and analysis error-prone.',
    'ai.context': 'Modern enterprise systems have deep dependency chains and distributed architectures. The goal was to build a platform that automatically extracts structured knowledge from source code and turns it into queryable documentation — so analysts, engineers, support teams, testers and managers can understand systems faster without reading thousands of lines of code. The platform also serves as an onboarding tool for new team members.',
    'ai.role1': 'Designed the product concept and defined capabilities for multiple user roles: analysts, engineers, support, testers and managers',
    'ai.role2': 'Built the entire system independently — from architecture to working product ready for team adoption',
    'ai.role3': 'Implemented automated documentation generation covering domain models, database schemas, architecture and API',
    'ai.role4': 'Created interactive AI workspace where analysts can ask questions about codebases in natural language',
    'ai.role5': 'Designed integration layer connecting the platform with existing enterprise tools and workflows',
    'ai.arch': 'The platform connects to source code repositories, automatically builds a structured understanding of the codebase and uses AI agents to generate documentation, answer questions and extract knowledge. Everything works through a single web interface with no manual setup required per repository.',
    'ai.solution1': 'Automatic codebase analysis: dependency graphs, module relationships and architectural patterns extracted without manual effort',
    'ai.solution2': 'Four documentation pipelines: domain, database, architecture and functional — generated by AI agents reading the code',
    'ai.solution3': 'AI chat with full codebase context: ask questions in natural language, get answers grounded in actual source code',
    'ai.solution4': 'Knowledge base: documentation is indexed semantically, so the AI can find relevant context across all projects',
    'ai.solution5': 'Enterprise integrations: connects to Confluence, Figma, Kaiten and email for unified workflow',
    'ai.challenge1': 'Making the platform work for large real-world repositories without manual configuration',
    'ai.challenge2': 'Ensuring AI-generated documentation is accurate and useful, not just plausible-sounding text',
    'ai.challenge3': 'Keeping knowledge up-to-date as code changes — not a one-time export but a living system',
    'ai.challenge4': 'Building something that analysts actually want to use, not just another internal tool',
    'ai.result1': 'Full-stack product with automated documentation generation, AI chat and knowledge base',
    'ai.result2': 'Teams can understand a new codebase in hours instead of days — analysts, support, testers and new hires',
    'ai.result3': 'Documentation stays current through automatic synchronization with code repositories',
    'ai.result4': 'Ready for deployment and adoption by development, analytics, support and management teams',
    'aiDelivery.problem': 'X5 Tech engineering teams faced challenges in adopting AI tools effectively. Each team used AI differently, context was poorly structured, and task decomposition remained manual. This created inconsistent quality and slow delivery cycles.',
    'aiDelivery.context': 'Large enterprise with multiple development teams working on web applications across different business domains. Need to standardize AI adoption while maintaining flexibility for different team contexts and project types.',
    'aiDelivery.role1': 'Created standardized skill-packs — sets of contexts, rules and templates for using AI tools in analytics and development',
    'aiDelivery.role2': 'Restructured task decomposition process: AI-assisted task creation with structured prompts and transfer to development',
    'aiDelivery.role3': 'Built AI Harness infrastructure — software layer around LLMs providing tool orchestration, memory and context management',
    'aiDelivery.role4': 'Implemented context structuring patterns for reliable AI agent behavior',
    'aiDelivery.role5': 'Trained and scaled AI practices across multiple teams through workshops and documentation',
    'aiDelivery.arch': 'Skill-packs → Context Templates → AI Tools → Harness Layer → Development Flow. The system provides standardized AI interaction patterns with structured contexts, enabling consistent quality across teams while allowing customization per project.',
    'aiDelivery.solution1': 'Skill-packs: curated sets of prompts, rules and context templates for specific tasks (requirements analysis, code review, documentation)',
    'aiDelivery.solution2': 'AI Harness: software infrastructure around LLMs providing tool management, output control and result monitoring',
    'aiDelivery.solution3': 'Structured task decomposition: AI generates task breakdowns with acceptance criteria, developers review and implement with AI support',
    'aiDelivery.solution4': 'Context management system: maintains relevant context across conversations and tool interactions',
    'aiDelivery.solution5': 'MCP (Model Context Protocol) integration for connecting AI agents with external systems and data sources',
    'aiDelivery.challenge1': 'Balancing standardization with flexibility — skill-packs need to work across different project types',
    'aiDelivery.challenge2': 'Ensuring AI reliability — structured contexts reduce hallucinations and improve output quality',
    'aiDelivery.challenge3': 'Scaling practices — successful patterns need to transfer across teams without losing effectiveness',
    'aiDelivery.challenge4': 'Measuring impact — quantifying AI contribution to delivery speed and quality',
    'aiDelivery.result1': '30-40% acceleration of "idea → feature implementation" cycle',
    'aiDelivery.result2': '3x reduction in incident localization and resolution time',
    'aiDelivery.result3': 'Standardized AI practices adopted by multiple teams',
    'aiDelivery.result4': 'AI Harness infrastructure enabling reliable autonomous agent behavior',
    'aiDelivery.result5': 'Task decomposition quality improved through AI-assisted creation with human review',
    'architecture.title': 'How I Think',
    'architecture.subtitle': 'From Problem to Result',
    'architecture.description': "I don't just document requirements — I work across the full spectrum from business problem understanding to architecture design and implementation.",
    'architecture.step1': 'Business Problem',
    'architecture.step2': 'Business Process',
    'architecture.step3': 'Requirements',
    'architecture.step4': 'System Context',
    'architecture.step5': 'Architecture',
    'architecture.step6': 'API / Data',
    'architecture.step7': 'Implementation',
    'architecture.step8': 'Automation / AI',
    'architecture.step9': 'Result',
    'aiResearch.title': 'AI Engineering & Research',
    'aiResearch.subtitle': 'System Analysis + Architecture + AI',
    'aiResearch.description': 'I research AI technologies and build production-oriented AI systems with them. My applied work includes designing and implementing AI Code Knowledge Platform — a full-stack platform for automated code knowledge extraction, graph-based analysis and documentation generation.',
    'aiResearch.llm.title': 'LLM & RAG Systems',
    'aiResearch.llm.description': 'Applying large language models with retrieval-augmented generation for code understanding, documentation and system analysis workflows.',
    'aiResearch.graph.title': 'Graph RAG & Code Graph',
    'aiResearch.graph.description': 'Exploring graph-based models for code analysis — transforming codebases into knowledge graphs for dependency analysis, context search and architecture understanding.',
    'aiResearch.semantic.title': 'Semantic Code Search',
    'aiResearch.semantic.description': 'Building systems that understand code semantically — enabling natural language queries over codebases, documentation and architectural decisions.',
    'aiResearch.agents.title': 'AI Agents & MCP',
    'aiResearch.agents.description': 'Developing AI agent architectures with Model Context Protocol for automated system analysis, requirement generation and technical documentation.',
    'aiResearch.analysis.title': 'AI-assisted Analysis',
    'aiResearch.analysis.description': 'Using AI to accelerate the analyst workflow itself — from requirement gathering and process modeling to architecture documentation and test generation.',
    'aiResearch.aickp.title': 'AI Code Knowledge Platform',
    'aiResearch.aickp.description': 'Designed and built a platform that automatically extracts knowledge from codebases and generates documentation. Used by analysts, engineers, support teams, testers and managers for system understanding and onboarding.',
    'aiResearch.mcpPlatform.title': 'Analyst Skill-packs & AI Agents',
    'aiResearch.mcpPlatform.description': 'Created standardized skill-packs — sets of prompts, context templates and rules for using AI tools in analytics workflows. Built agent configurations for requirements analysis, code review and documentation generation.',
    'aiResearch.mcp.title': 'MCP Servers & Integrations',
    'aiResearch.mcp.description': 'Built and operate MCP (Model Context Protocol) servers for AI agent integration with enterprise systems — enabling agents to access code, documentation, project management tools and communication platforms.',
    'footer.title': "Let's work together",
    'footer.description': 'Open to senior system analyst, solution architecture and AI-focused engineering roles.',
    'footer.rights': 'All rights reserved',
    'footer.builtWith': 'Built with',
    'theme.toggle': 'Toggle theme',
    'language.toggle': 'Toggle language',
  },
  ru: {
    'nav.about': 'Обо мне',
    'nav.experience': 'Опыт',
    'nav.projects': 'Проекты',
    'nav.architecture': 'Архитектура',
    'nav.aiResearch': 'AI исследования',
    'nav.contact': 'Контакты',
    'hero.title': 'Системы и AI',
    'hero.subtitle': 'Системный аналитик / Системы и AI',
    'hero.name': 'Мансур Какушкин',
    'hero.description': 'Проектирую сложные системы, интеграции и AI-решения — от бизнес-задачи до архитектуры и реализации.',
    'hero.downloadCV': 'Скачать резюме',
    'hero.contactMe': 'Связаться',
    'hero.viewExperience': 'Посмотреть опыт',
    'hero.selectedProjects': 'Избранные проекты',
    'hero.scrollExplore': 'Листайте дальше',
    'about.title': 'Обо мне',
    'about.subtitle': 'Проектирую корпоративные системы по полному циклу — от бизнес-задачи до архитектуры, API, данных, интеграций и AI-автоматизации.',
    'about.description1': 'Системный аналитик с 7+ годами опыта в enterprise-технологиях. Работал в X5 и Сбер — проектировал сложные информационные системы, интеграции и автоматизация в масштабе.',
    'about.description2': 'Владею задачами от начала до конца: перевожу бизнес-логику в системные требования, проектирую архитектуру, определяю API и структуры данных, строю интеграции и довожу до продакшена. Работаю по полному циклу — бизнес-процесс → требования → системный дизайн → реализация → результат.',
    'about.description3': 'Также строю AI-системы и применяю LLM, RAG, Graph RAG, графы знаний и AI-агентов в инженерной работе. Спроектировал и реализовал AI Code Knowledge Platform — full-stack платформу для автоматического извлечения знаний из кода, графового анализа и AI-генерации документации. Участвовал в создании продукта, получившего патент RU2732071C1 на автоматизированный правовой анализ.',
    'about.description4': 'Открыт к ролям Senior System Analyst, Solution Architect или AI-инженерных позиций, где можно работать со сложными системами, интеграциями и архитектурой в масштабе.',
    'about.rolesTitle': 'Работаю на стыке:',
    'about.roles': 'Системная архитектура,Архитектура интеграций,Проектирование API,Data Pipelines,AI / LLM / RAG,Knowledge Graphs,MCP / AI Agents,Software Engineering',
    'about.impactTitle': 'Избранные результаты',
    'about.impact1Label': 'Оптимизация ресурсов',
    'about.impact1Value': '5x',
    'about.impact1Desc': 'за счёт автоматизации систем',
    'about.impact2Label': 'Ускорение delivery',
    'about.impact2Value': '30–40%',
    'about.impact2Desc': 'цикл «идея → фича»',
    'about.impact3Label': 'Инциденты',
    'about.impact3Value': '~3x',
    'about.impact3Desc': 'быстрее в продакшене',
    'about.impact4Label': 'Патент',
    'about.impact4Value': 'RU2732071C1',
    'about.impact4Desc': 'участник реализации — автоматизированный правовой анализ',
    'experience.title': 'Опыт работы',
    'experience.subtitle': 'Карьерный путь',
    'experience.x5tech.company': 'X5 Tech',
    'experience.x5tech.senior.role': 'Старший системный аналитик',
    'experience.x5tech.senior.period': 'Сентябрь 2025 — настоящее время (1 год)',
    'experience.x5tech.senior.location': 'Москва / Удалённо',
    'experience.x5tech.senior.highlight1': 'Координирую delivery в 2 проектных командах и 1 продуктовой — определяю приоритеты, ставлю задачи и управляю ежедневной работой разработчиков, аналитиков и QA.',
    'experience.x5tech.senior.highlight2': 'Перестроил процесс от требований к разработке вокруг AI-спецификаций, документации в Git, автоматической генерации тестов и AI-код-ревью — ускорил цикл «идея → фича» на 30–40%, позволив команде справляться с объёмом, который потребовал бы ~1,5× штата.',
    'experience.x5tech.senior.highlight3': 'Внедрил AI-assisted расследование инцидентов со структурированным техническим контекстом и MCP-интеграциями с task-трекерами, сократив время решения инцидентов в production с 2–3 дней до менее 1 дня.',
    'experience.x5tech.senior.highlight4': 'Задумал, спроектировал и реализовал AI Code Knowledge Platform — full-stack систему (Python, React, MCP, Memgraph), автоматически извлекающую знания из кодовых баз, генерирующую документацию и предоставляющую AI-чат по системному контексту. Масштабировал: личный рабочий процесс → 5 аналитиков → несколько команд. Сейчас в пользовательском тестировании (аналитики, разработчики, поддержка, QA).',
    'experience.x5tech.senior.highlight5': 'Встроил AI во все этапы delivery-пайплайна — инженерия требований, генерация документации, создание тест-кейсов, ревью API-спецификаций и автоматический анализ кода — превратив AI из эксперимента в базовый инструмент.',
    'experience.x5tech.senior.highlight6': 'Привёл всю проектную документацию к единому формату с шаблонами, референсами и правилами использования, обеспечив единый onboarding и передачу контекста между командами.',
    'experience.x5tech.senior.highlight7': 'Масштабировал AI-практики на другие команды через воркшопы, обучение и кросс-командное взаимодействие.',
    'experience.x5tech.analyst.role': 'Системный аналитик',
    'experience.x5tech.analyst.period': 'Октябрь 2023 — Август 2025 (1 год 11 месяцев)',
    'experience.x5tech.analyst.location': 'Москва / Удалённо',
    'experience.x5tech.analyst.highlight1': 'Спроектировал архитектуру крупной платформы налогового мониторинга с ~7 внешними интеграциями (SAP, ФНС, сервисы подписания/ЭЦП), координируя интеграционные контракты между бизнес-процессами и внутренними сервисами. Решение обслуживает 9 юрлиц, 4 внутренних подразделения и 40+ пользователей.',
    'experience.x5tech.analyst.highlight2': 'Спроектировал schema-driven подход: пайплайн XSD → JSON Schema → UI, устранив необходимость участия разработчиков при поддержке новых версий схем — экранные формы адаптируются автоматически при обновлении схемы аналитиком.',
    'experience.x5tech.analyst.highlight3': 'Интегрировал новые источники данных для автоматизированной генерации отчётов, сократив ручную нагрузку эквивалентом ~2 FTE.',
    'experience.x5tech.analyst.highlight4': 'Определил API-контракты и интеграционные интерфейсы между SAP, PostgreSQL, ClickHouse и внутренними сервисами, координируя требования между командами.',
    'experience.x5tech.analyst.highlight5': 'Создавал дашборды для мониторинга системы в Grafana и реализовывал логику алертов для отслеживания состояния платформы в production.',
    'experience.x5tech.analyst.highlight6': 'Выполнял функции системного и бизнес-аналитика: сбор и проработка требований, постановка задач разработчикам, приоритизация и контроль реализации.',
    'experience.extrum.company': 'Extrum',
    'experience.extrum.role': 'Бизнес / Системный аналитик',
    'experience.extrum.period': 'Ноябрь 2022 — Сентябрь 2023 (11 месяцев)',
    'experience.extrum.location': 'Москва',
    'experience.extrum.highlight1': 'Собирал требования, готовил технические спецификации и согласовывал архитектурные решения с заказчиками и командой разработки.',
    'experience.extrum.highlight2': 'Управлял бэклогом, приоритетами и сроками; формировал команду разработки и направлял работу.',
    'experience.extrum.highlight3': 'Тестировал функционал, выявлял проблемы и устранял их через структурированное управление задачами.',
    'experience.smartauto.company': 'ООО Умная Автоматизация',
    'experience.smartauto.role': 'Системный аналитик',
    'experience.smartauto.period': 'Ноябрь 2022 — Апрель 2023 (6 месяцев)',
    'experience.smartauto.location': 'Москва',
    'experience.smartauto.highlight1': 'Настроил и внедрил продукт Smart Automation у 3 enterprise-заказчиков, создавал проектную документацию и координировал поставку.',
    'experience.smartauto.highlight2': 'Выявил 15 критических блокирующих дефектов, приоритизировал и устранил их; добавил фичи, улучшившие рабочие процессы пользователей и администраторов.',
    'experience.sber.role': 'Системный аналитик',
    'experience.sber.period': 'Декабрь 2018 — Октябрь 2022 (3 года 11 месяцев)',
    'experience.sber.location': 'Москва',
    'experience.sber.highlight1': 'Со-создал сервис генерации документов на основе ML с F-мерой 90% во взаимодействии с командой Data Science.',
    'experience.sber.highlight2': 'Разрабатывал и поддерживал проекты LegalTech, автоматизирующие due diligence в корпоративном кредитовании.',
    'experience.sber.highlight3': 'Создал внутренний аналитический сервис для команды аудиторов; разработал DSL-инструменты на Python для автоматизированного due diligence.',
    'projects.title': 'Избранные проекты',
    'projects.subtitle': 'Кейсы',
    'projects.tax.title': 'Система налогового мониторинга',
    'projects.tax.subtitle': 'SAP / ФНС / Микросервисы / PostgreSQL / ClickHouse / Airflow',
    'projects.tax.description': 'Система, интегрированная с SAP и корпоративными системами для мониторинга ФНС. Микросервисная архитектура для 40+ пользователей в 9 юридических лицах.',
    'projects.tax.metric1': 'Оптимизация ресурсов в 5 раз',
    'projects.tax.metric2': '9 юридических лиц',
    'projects.tax.metric3': '40+ пользователей',
    'projects.schema.title': 'Автоматизация на основе схем',
    'projects.schema.subtitle': 'XSD → JSON Schema → Python',
    'projects.schema.description': 'Автоматизированный конвейер обработки схем документов, преобразующий XSD-схемы в JSON Schema и генерирующий скрипты обработки — снижение ручной работы аналитика.',
    'projects.schema.metric1': 'Обработка в 5 раз быстрее',
    'projects.schema.metric2': 'Снижение ручной работы',
    'projects.aiDelivery.title': 'AI Delivery Transformation',
    'projects.aiDelivery.subtitle': 'Skill-packs / Контекст / AI Harness',
    'projects.aiDelivery.description': 'Полная AI-трансформация процессов delivery в X5 Tech. Создание стандартизированных skill-packs для AI-инструментов, реструктуризация декомпозиции задач, построение AI Harness инфраструктуры — ускорение цикла «идея → фича» на 30–40%.',
    'projects.aiDelivery.metric1': 'Delivery быстрее на 30–40%',
    'projects.aiDelivery.metric2': 'Инциденты решаются в 3 раза быстрее',
    'projects.aiDelivery.metric3': 'Масштабировано на несколько команд',
    'projects.ai.title': 'AI Code Knowledge Platform',
    'projects.ai.subtitle': 'Graph RAG / AI Agents / MCP / Knowledge Graph',
    'projects.ai.description': 'Спроектировал и реализовал end-to-end платформу для автоматического извлечения знаний из исходного кода. Преобразует репозитории в графы знаний, генерирует документацию через AI-агентов и предоставляет AI-чат с мульти-проектным контекстом и MCP-интеграциями.',
    'projects.ai.metric1': 'Full-stack платформа',
    'projects.ai.metric2': '4 пайплайна документации',
    'projects.ai.metric3': 'AI чат + MCP',
    'projects.viewCaseStudy': 'Посмотреть кейс',
    'casestudy.problem': 'Проблема',
    'casestudy.context': 'Контекст',
    'casestudy.myRole': 'Моя роль',
    'casestudy.architecture': 'Архитектура',
    'casestudy.solution': 'Техническое решение',
    'casestudy.challenges': 'Сложности',
    'casestudy.result': 'Результат',
    'casestudy.technologies': 'Технологии',
    'casestudy.back': 'Назад к проектам',
    'casestudy.label': 'Кейс',
    'tax.problem': 'Крупной группе предприятий требовалась новая автоматизированная система налогового мониторинга — АИС Налог 3 — для замены ручного процесса отчётности перед ФНС. Существующий процесс включал извлечение данных из множества корпоративных систем, включая SAP, что было трудоёмким и подверженным ошибкам. Решение разрабатывалось с упором на автоматизацию работы пользователей в масштабе 9 юридических лиц.',
    'tax.context': 'Система должна была обслуживать 40+ пользователей в группе из 9 юридических лиц. Источниками данных выступали SAP ERP и другие корпоративные системы. Архитектура требовала микросервисов для обработки различных аспектов извлечения данных, валидации и отчётности.',
    'tax.role1': 'Системный анализ и сбор требований от бизнес-стейкхолдеров',
    'tax.role2': 'Проектирование интеграционной архитектуры между SAP, PostgreSQL, ClickHouse и внутренними системами',
    'tax.role3': 'Определение API-контрактов и структур данных для микросервисного взаимодействия',
    'tax.role4': 'Техническая документация и записи архитектурных решений',
    'tax.role5': 'Координация между бизнесом, разработкой и эксплуатацией',
    'tax.arch': 'Микросервисная архитектура с выделенными сервисами для извлечения, трансформации, валидации данных и отчётности. Интеграционный слой SAP для синхронизации данных. PostgreSQL для транзакционных данных, ClickHouse для аналитических запросов и отчётности. Airflow для оркестрации пайплайнов данных.',
    'tax.solution1': 'REST API слой для межсервисного взаимодействия с чётко определёнными контрактами',
    'tax.solution2': 'ETL-пайплайны под управлением Airflow для извлечения и трансформации данных',
    'tax.solution3': 'Schema-driven валидация данных для обеспечения соответствия требованиям ФНС',
    'tax.solution4': 'Слой кеширования для часто запрашиваемых справочных данных',
    'tax.solution5': 'Мониторинг и алертинг для состояния пайплайнов данных',
    'tax.challenge1': 'Сложные структуры данных в 9 различных юридических лицах с разными конфигурациями',
    'tax.challenge2': 'Интеграция с SAP, требующая глубокого понимания корпоративных моделей данных',
    'tax.challenge3': 'Жёсткие требования ФНС к соответствию с нулевой толерантностью к ошибкам данных',
    'tax.challenge4': 'Требования к производительности для больших объёмов данных в аналитических запросах',
    'tax.result1': '5-кратная оптимизация по времени и использованию ресурсов за счёт автоматизации',
    'tax.result2': 'Успешное обслуживание 40+ пользователей в 9 юридических лицах',
    'tax.result3': 'Устранено ручное извлечение данных и ошибки валидации',
    'tax.result4': 'Сокращено время генерации отчётов с дней до часов',
    'schema.problem': 'Ранее для каждой XSD-схемы разработчикам приходилось вручную создавать экранные формы — это требовало участия разработчиков при каждой новой версии схемы. Это создавало узкое место: любое изменение XSD означало работу разработчиков по обновлению соответствующих форм.',
    'schema.context': 'Спроектирован универсальный механизм: JSON Schema полуавтоматически генерируется из XSD и передаётся на фронтенд, который автоматически рисует экранные формы под конкретную версию XSD. Теперь при изменении XSD аналитику достаточно обновить JSON Schema — экранные формы адаптируются автоматически без участия разработчиков.',
    'schema.role1': 'Выявил возможность автоматизации в процессе обработки схем',
    'schema.role2': 'Спроектировал конвейер трансформации XSD → JSON Schema → Python',
    'schema.role3': 'Реализовал Python-скрипты для автоматической конвертации схем и генерации кода',
    'schema.role4': 'Проверил точность результатов относительно ручной обработки',
    'schema.arch': 'Архитектура конвейера: XSD источник → слой парсинга → генерация JSON Schema → генерация Python-скриптов → валидация → выходные артефакты. Каждый этап модульный и может быть расширен для новых типов схем или форматов вывода.',
    'schema.solution1': 'Парсер XSD на Python, извлекающий определения типов, ограничения и связи',
    'schema.solution2': 'Полуавтоматическая генерация JSON Schema из XSD с учётом бизнес-логики',
    'schema.solution3': 'Бэкенд использует библиотеку для конвертации JSON → XML. JSON Schema передаётся на фронтенд, который автоматически рисует поля формы и собирает данные в FormData',
    'schema.solution4': 'Аналитику достаточно загружать обновлённые JSON Schema при изменении XSD — разработчики не участвуют в процессе',
    'schema.challenge1': 'Сложные возможности XSD, включая пространства имён, наследование и пользовательские типы',
    'schema.challenge2': 'Поддержание точности при автоматических трансформациях',
    'schema.challenge3': 'Обработка граничных случаев в определениях схем без вмешательства человека',
    'schema.result1': '5-кратное ускорение обработки схем за счёт автоматизации',
    'schema.result2': 'Значительное сокращение ручной работы аналитиков и разработчиков',
    'schema.result3': 'Ускорение реагирования на запросы изменений схем',
    'schema.result4': 'Снижение ошибок при переводе из схемы в код',
    'schema.result5': 'Разработка полностью исключена из процесса — всё работает автоматически',
    'ai.problem': 'Системные аналитики и инженеры тратят значительное время на понимание существующих кодовых баз — отслеживание зависимостей, поиск контекста и ручное написание документации. Знания о системах хранятся в головах людей и разрозненных документах, что замедляет онбординг и делает анализ подверженным ошибкам.',
    'ai.context': 'Современные корпоративные системы имеют глубокие цепочки зависимостей и распределённые архитектуры. Цель состояла в создании платформы, которая автоматически извлекает структурированные знания из исходного кода и превращает их в запрашиваемую документацию — чтобы аналитики, инженеры, поддержка, тестировщики и менеджеры могли понимать системы быстрее, не читая тысячи строк кода. Платформа также служит инструментом онбординга для новых сотрудников.',
    'ai.role1': 'Спроектировал концепт продукта и определил возможности для разных ролей: аналитики, инженеры, поддержка, тестировщики и менеджеры',
    'ai.role2': 'Собрал всю систему самостоятельно — от архитектуры до готового продукта, готового к использованию командами',
    'ai.role3': 'Реализовал автоматическую генерацию документации, покрывающей доменные модели, схемы БД, архитектуру и API',
    'ai.role4': 'Создал интерактивное AI-рабочее пространство, где аналитики могут задавать вопросы о кодовых базах на естественном языке',
    'ai.role5': 'Спроектировал интеграционный слой, связывающий платформу с существующими корпоративными инструментами',
    'ai.arch': 'Платформа подключается к репозиториям исходного кода, автоматически выстраивает структурированное понимание кодовой базы и использует AI-агентов для генерации документации, ответов на вопросы и извлечения знаний. Всё работает через единый веб-интерфейс без ручной настройки под каждый репозиторий.',
    'ai.solution1': 'Автоматический анализ кодовой базы: графы зависимостей, связи модулей и архитектурные паттерны без ручного труда',
    'ai.solution2': 'Четыре пайплайна документации: доменная, БД, архитектурная и функциональная — генерируются AI-агентами',
    'ai.solution3': 'AI-чат с полным контекстом кодовой базы: вопросы на естественном языке, ответы на основе реального кода',
    'ai.solution4': 'База знаний: документация индексируется семантически, AI находит релевантный контекст по всем проектам',
    'ai.solution5': 'Корпоративные интеграции: подключение к Confluence, Figma, Kaiten и почте для единого рабочего процесса',
    'ai.challenge1': 'Обеспечение работы с крупными реальными репозиториями без ручной конфигурации',
    'ai.challenge2': 'Точность и полезность AI-документации — не просто правдоподобный текст, а действительно полезное содержание',
    'ai.challenge3': 'Поддержание актуальности знаний при изменениях в коде — не разовый экспорт, а живая система',
    'ai.challenge4': 'Создание продукта, которым аналитики действительно захотят пользоваться, а не ещё одного внутреннего инструмента',
    'ai.result1': 'Full-stack продукт с автоматической генерацией документации, AI-чатом и базой знаний',
    'ai.result2': 'Команды могут понять новую кодовую базу за часы вместо дней — аналитики, поддержка, тестировщики и новые сотрудники',
    'ai.result3': 'Документация остаётся актуальной через автоматическую синхронизацию с кодовыми репозиториями',
    'ai.result4': 'Готова к развёртыванию и использованию командами разработки, аналитики, поддержки и менеджмента',
    'aiDelivery.problem': 'Команды X5 Tech сталкивались с проблемами в эффективном внедрении AI-инструментов. Каждая команда использовала AI по-разному, контекст был плохо структурирован, а декомпозиция задач оставалась ручной. Это создавало непоследовательное качество и медленные циклы delivery.',
    'aiDelivery.context': 'Крупное предприятие с несколькими командами разработки, работающими над веб-приложениями различных бизнес-доменов. Необходимость стандартизировать внедрение AI, сохраняя гибкость для разных контекстов команд и типов проектов.',
    'aiDelivery.role1': 'Создание стандартизированных skill-packs — наборов контекстов, правил и шаблонов для использования AI-инструментов в аналитике и разработке',
    'aiDelivery.role2': 'Реструктуризация процесса декомпозиции задач: AI-ассистированное создание задач со структурированными промптами и передача в разработку',
    'aiDelivery.role3': 'Построение AI Harness инфраструктуры — программный слой вокруг LLM, обеспечивающий оркестрацию инструментов, память и управление контекстом',
    'aiDelivery.role4': 'Внедрение паттернов структурирования контекста для надёжного поведения AI-агентов',
    'aiDelivery.role5': 'Обучение и масштабирование AI-практик на несколько команд через воркшопы и документацию',
    'aiDelivery.arch': 'Skill-packs → Шаблоны контекста → AI-инструменты → Harness-слой → Development-флоу. Система обеспечивает стандартизированные паттерны взаимодействия с AI со структурированными контекстами, обеспечивая согласованное качество между командами с возможностью кастомизации под проект.',
    'aiDelivery.solution1': 'Skill-packs: курированные наборы промптов, правил и шаблонов контекста для конкретных задач (анализ требований, код-ревью, документация)',
    'aiDelivery.solution2': 'AI Harness: программная инфраструктура вокруг LLM, обеспечивающая управление инструментами, контроль вывода и мониторинг результатов',
    'aiDelivery.solution3': 'Структурированная декомпозиция задач: AI генерирует разбивку задач с критериями приёмки, разработчики проверяют и реализуют с поддержкой AI',
    'aiDelivery.solution4': 'Система управления контекстом: поддержание релевантного контекста в разговорах и взаимодействиях с инструментами',
    'aiDelivery.solution5': 'Интеграция MCP (Model Context Protocol) для подключения AI-агентов к внешним системам и источникам данных',
    'aiDelivery.challenge1': 'Баланс между стандартизацией и гибкостью — skill-packs должны работать для разных типов проектов',
    'aiDelivery.challenge2': 'Обеспечение надёжности AI — структурированные контексты снижают галлюцинации и улучшают качество вывода',
    'aiDelivery.challenge3': 'Масштабирование практик — успешные паттерны должны переноситься между командами без потери эффективности',
    'aiDelivery.challenge4': 'Измерение влияния — квантификация вклада AI в скорость и качество delivery',
    'aiDelivery.result1': '30–40% ускорение цикла «идея → реализация фичи»',
    'aiDelivery.result2': '3-кратное сокращение времени локализации и решения инцидентов',
    'aiDelivery.result3': 'Стандартизированные AI-практики, внедрённые в нескольких командах',
    'aiDelivery.result4': 'AI Harness инфраструктура, обеспечивающая надёжное поведение автономных агентов',
    'aiDelivery.result5': 'Улучшение качества декомпозиции задач через AI-ассистированное создание с человеческим контролем',
    'architecture.title': 'Как я мыслю',
    'architecture.subtitle': 'От проблемы к результату',
    'architecture.description': 'Я не просто документирую требования — я работаю во всем спектре: от понимания бизнес-задачи до проектирования архитектуры и реализации.',
    'architecture.step1': 'Бизнес-задача',
    'architecture.step2': 'Бизнес-процесс',
    'architecture.step3': 'Требования',
    'architecture.step4': 'Системный контекст',
    'architecture.step5': 'Архитектура',
    'architecture.step6': 'API / Данные',
    'architecture.step7': 'Реализация',
    'architecture.step8': 'Автоматизация / AI',
    'architecture.step9': 'Результат',
    'aiResearch.title': 'AI-инжиниринг и исследования',
    'aiResearch.subtitle': 'Системный анализ + Архитектура + AI',
    'aiResearch.description': 'Исследую AI-технологии и строю на их основе production-ориентированные AI-системы. Моя прикладная работа включает проектирование и реализацию AI Code Knowledge Platform — full-stack системы для автоматического извлечения знаний из кода, графового анализа и генерации документации.',
    'aiResearch.llm.title': 'LLM и RAG системы',
    'aiResearch.llm.description': 'Применение больших языковых моделей с генерацией с дополнительным поиском для понимания кода, документации и рабочих процессов системного анализа.',
    'aiResearch.graph.title': 'Graph RAG и Code Graph',
    'aiResearch.graph.description': 'Исследование графовых моделей для анализа кода — преобразование кодовых баз в графы знаний для анализа зависимостей, контекстного поиска и понимания архитектуры.',
    'aiResearch.semantic.title': 'Семантический поиск кода',
    'aiResearch.semantic.description': 'Создание систем, которые понимают код семантически — обеспечивая запросы на естественном языке по кодовым базам, документации и архитектурным решениям.',
    'aiResearch.agents.title': 'AI агенты и MCP',
    'aiResearch.agents.description': 'Разработка архитектур AI-агентов с Model Context Protocol для автоматизированного системного анализа, генерации требований и технической документации.',
    'aiResearch.analysis.title': 'AI-ассистированный анализ',
    'aiResearch.analysis.description': 'Использование AI для ускорения самого рабочего процесса аналитика — от сбора требований и моделирования процессов до документирования архитектуры и генерации тестов.',
    'aiResearch.aickp.title': 'AI Code Knowledge Platform',
    'aiResearch.aickp.description': 'Спроектировал и реализовал платформу, автоматически извлекающую знания из кодовых баз и генерирующую документацию. Используется аналитиками, инженерами, поддержкой, тестировщиками и менеджерами для понимания систем и онбординга.',
    'aiResearch.mcpPlatform.title': 'Skill-packs и AI-агенты для аналитиков',
    'aiResearch.mcpPlatform.description': 'Создание стандартизированных skill-packs — наборов промптов, шаблонов контекста и правил для использования AI-инструментов в аналитических процессах. Настройка агентов для анализа требований, код-ревью и генерации документации.',
    'aiResearch.mcp.title': 'MCP-серверы и интеграции',
    'aiResearch.mcp.description': 'Создание и эксплуатация MCP-серверов (Model Context Protocol) для интеграции AI-агентов с корпоративными системами — доступ агентов к коду, документации, инструментам управления проектами и коммуникационным платформам.',
    'footer.title': 'Давайте работать вместе',
    'footer.description': 'Открыт для позиций системного аналитика, архитектора решений и AI-инженера.',
    'footer.rights': 'Все права защищены',
    'footer.builtWith': 'Создано с помощью',
    'theme.toggle': 'Переключить тему',
    'language.toggle': 'Переключить язык',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
